//! Code generated by `tools/generate` - manual edits will be overwritten.

const std = @import("std");
const data = @import("../data.zig");

const assert = std.debug.assert;

const Specie = data.Specie;
const Stats = data.Stats;
const Type = data.Type;

/// Species constants representing all legal moves, plus the sentinel `None`.
/// The sentinal value is guaranteed to be bit-equivalent to `0` and can be
/// used to represent a null-pointer equivalent without using the additional
/// byte that `?Species` would entail.
///
/// *See:* https://pkmn.cc/pokered/constants/pokedex_constants.asm
///
pub const Species = enum(u8) {
    None,
    Bulbasaur,
    Ivysaur,
    Venusaur,
    Charmander,
    Charmeleon,
    Charizard,
    Squirtle,
    Wartortle,
    Blastoise,
    Caterpie,
    Metapod,
    Butterfree,
    Weedle,
    Kakuna,
    Beedrill,
    Pidgey,
    Pidgeotto,
    Pidgeot,
    Rattata,
    Raticate,
    Spearow,
    Fearow,
    Ekans,
    Arbok,
    Pikachu,
    Raichu,
    Sandshrew,
    Sandslash,
    NidoranF,
    Nidorina,
    Nidoqueen,
    NidoranM,
    Nidorino,
    Nidoking,
    Clefairy,
    Clefable,
    Vulpix,
    Ninetales,
    Jigglypuff,
    Wigglytuff,
    Zubat,
    Golbat,
    Oddish,
    Gloom,
    Vileplume,
    Paras,
    Parasect,
    Venonat,
    Venomoth,
    Diglett,
    Dugtrio,
    Meowth,
    Persian,
    Psyduck,
    Golduck,
    Mankey,
    Primeape,
    Growlithe,
    Arcanine,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Abra,
    Kadabra,
    Alakazam,
    Machop,
    Machoke,
    Machamp,
    Bellsprout,
    Weepinbell,
    Victreebel,
    Tentacool,
    Tentacruel,
    Geodude,
    Graveler,
    Golem,
    Ponyta,
    Rapidash,
    Slowpoke,
    Slowbro,
    Magnemite,
    Magneton,
    Farfetchd,
    Doduo,
    Dodrio,
    Seel,
    Dewgong,
    Grimer,
    Muk,
    Shellder,
    Cloyster,
    Gastly,
    Haunter,
    Gengar,
    Onix,
    Drowzee,
    Hypno,
    Krabby,
    Kingler,
    Voltorb,
    Electrode,
    Exeggcute,
    Exeggutor,
    Cubone,
    Marowak,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing,
    Weezing,
    Rhyhorn,
    Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    Horsea,
    Seadra,
    Goldeen,
    Seaking,
    Staryu,
    Starmie,
    MrMime,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    Tauros,
    Magikarp,
    Gyarados,
    Lapras,
    Ditto,
    Eevee,
    Vaporeon,
    Jolteon,
    Flareon,
    Porygon,
    Omanyte,
    Omastar,
    Kabuto,
    Kabutops,
    Aerodactyl,
    Snorlax,
    Articuno,
    Zapdos,
    Moltres,
    Dratini,
    Dragonair,
    Dragonite,
    Mewtwo,
    Mew,

    comptime {
        assert(@sizeOf(Species) == 1);
    }

    pub inline fn get(id: Species) *const Specie {
        assert(id != .None);
        return &SPECIES[@enumToInt(id) - 1];
    }
};

/// Basic raw species data - names and descriptions are handled elswhere.
///
/// **NOTE:** just like in-game, each Pokémon has two types (Pokémon Showdown
/// elides the second type if its redundant, but dealing with variable length
/// and alignment arrays is more trouble and more often than not amounts to the
/// same space requirements).
///
/// *See:* https://pkmn.cc/pokered/data/pokemon/base_stats
///
const SPECIES = [_]Specie{ Specie{
    .id = .Bulbasaur,
    .stats = Stats(u8){
        .hp = 45,
        .atk = 49,
        .def = 49,
        .spe = 45,
        .spc = 65,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Ivysaur,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 62,
        .def = 63,
        .spe = 60,
        .spc = 80,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Venusaur,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 82,
        .def = 83,
        .spe = 80,
        .spc = 100,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Charmander,
    .stats = Stats(u8){
        .hp = 39,
        .atk = 52,
        .def = 43,
        .spe = 65,
        .spc = 50,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Charmeleon,
    .stats = Stats(u8){
        .hp = 58,
        .atk = 64,
        .def = 58,
        .spe = 80,
        .spc = 65,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Charizard,
    .stats = Stats(u8){
        .hp = 78,
        .atk = 84,
        .def = 78,
        .spe = 100,
        .spc = 85,
    },
    .types = [_]Type{ .Fire, .Flying },
}, Specie{
    .id = .Squirtle,
    .stats = Stats(u8){
        .hp = 44,
        .atk = 48,
        .def = 65,
        .spe = 43,
        .spc = 50,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Wartortle,
    .stats = Stats(u8){
        .hp = 59,
        .atk = 63,
        .def = 80,
        .spe = 58,
        .spc = 65,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Blastoise,
    .stats = Stats(u8){
        .hp = 79,
        .atk = 83,
        .def = 100,
        .spe = 78,
        .spc = 85,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Caterpie,
    .stats = Stats(u8){
        .hp = 45,
        .atk = 30,
        .def = 35,
        .spe = 45,
        .spc = 20,
    },
    .types = [_]Type{ .Bug, .Bug },
}, Specie{
    .id = .Metapod,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 20,
        .def = 55,
        .spe = 30,
        .spc = 25,
    },
    .types = [_]Type{ .Bug, .Bug },
}, Specie{
    .id = .Butterfree,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 45,
        .def = 50,
        .spe = 70,
        .spc = 80,
    },
    .types = [_]Type{ .Bug, .Flying },
}, Specie{
    .id = .Weedle,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 35,
        .def = 30,
        .spe = 50,
        .spc = 20,
    },
    .types = [_]Type{ .Bug, .Poison },
}, Specie{
    .id = .Kakuna,
    .stats = Stats(u8){
        .hp = 45,
        .atk = 25,
        .def = 50,
        .spe = 35,
        .spc = 25,
    },
    .types = [_]Type{ .Bug, .Poison },
}, Specie{
    .id = .Beedrill,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 80,
        .def = 40,
        .spe = 75,
        .spc = 45,
    },
    .types = [_]Type{ .Bug, .Poison },
}, Specie{
    .id = .Pidgey,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 45,
        .def = 40,
        .spe = 56,
        .spc = 35,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Pidgeotto,
    .stats = Stats(u8){
        .hp = 63,
        .atk = 60,
        .def = 55,
        .spe = 71,
        .spc = 50,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Pidgeot,
    .stats = Stats(u8){
        .hp = 83,
        .atk = 80,
        .def = 75,
        .spe = 91,
        .spc = 70,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Rattata,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 56,
        .def = 35,
        .spe = 72,
        .spc = 25,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Raticate,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 81,
        .def = 60,
        .spe = 97,
        .spc = 50,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Spearow,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 60,
        .def = 30,
        .spe = 70,
        .spc = 31,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Fearow,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 90,
        .def = 65,
        .spe = 100,
        .spc = 61,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Ekans,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 60,
        .def = 44,
        .spe = 55,
        .spc = 40,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Arbok,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 85,
        .def = 69,
        .spe = 80,
        .spc = 65,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Pikachu,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 55,
        .def = 30,
        .spe = 90,
        .spc = 50,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Raichu,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 90,
        .def = 55,
        .spe = 100,
        .spc = 90,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Sandshrew,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 75,
        .def = 85,
        .spe = 40,
        .spc = 30,
    },
    .types = [_]Type{ .Ground, .Ground },
}, Specie{
    .id = .Sandslash,
    .stats = Stats(u8){
        .hp = 75,
        .atk = 100,
        .def = 110,
        .spe = 65,
        .spc = 55,
    },
    .types = [_]Type{ .Ground, .Ground },
}, Specie{
    .id = .NidoranF,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 47,
        .def = 52,
        .spe = 41,
        .spc = 40,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Nidorina,
    .stats = Stats(u8){
        .hp = 70,
        .atk = 62,
        .def = 67,
        .spe = 56,
        .spc = 55,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Nidoqueen,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 82,
        .def = 87,
        .spe = 76,
        .spc = 75,
    },
    .types = [_]Type{ .Poison, .Ground },
}, Specie{
    .id = .NidoranM,
    .stats = Stats(u8){
        .hp = 46,
        .atk = 57,
        .def = 40,
        .spe = 50,
        .spc = 40,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Nidorino,
    .stats = Stats(u8){
        .hp = 61,
        .atk = 72,
        .def = 57,
        .spe = 65,
        .spc = 55,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Nidoking,
    .stats = Stats(u8){
        .hp = 81,
        .atk = 92,
        .def = 77,
        .spe = 85,
        .spc = 75,
    },
    .types = [_]Type{ .Poison, .Ground },
}, Specie{
    .id = .Clefairy,
    .stats = Stats(u8){
        .hp = 70,
        .atk = 45,
        .def = 48,
        .spe = 35,
        .spc = 60,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Clefable,
    .stats = Stats(u8){
        .hp = 95,
        .atk = 70,
        .def = 73,
        .spe = 60,
        .spc = 85,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Vulpix,
    .stats = Stats(u8){
        .hp = 38,
        .atk = 41,
        .def = 40,
        .spe = 65,
        .spc = 65,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Ninetales,
    .stats = Stats(u8){
        .hp = 73,
        .atk = 76,
        .def = 75,
        .spe = 100,
        .spc = 100,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Jigglypuff,
    .stats = Stats(u8){
        .hp = 115,
        .atk = 45,
        .def = 20,
        .spe = 20,
        .spc = 25,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Wigglytuff,
    .stats = Stats(u8){
        .hp = 140,
        .atk = 70,
        .def = 45,
        .spe = 45,
        .spc = 50,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Zubat,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 45,
        .def = 35,
        .spe = 55,
        .spc = 40,
    },
    .types = [_]Type{ .Poison, .Flying },
}, Specie{
    .id = .Golbat,
    .stats = Stats(u8){
        .hp = 75,
        .atk = 80,
        .def = 70,
        .spe = 90,
        .spc = 75,
    },
    .types = [_]Type{ .Poison, .Flying },
}, Specie{
    .id = .Oddish,
    .stats = Stats(u8){
        .hp = 45,
        .atk = 50,
        .def = 55,
        .spe = 30,
        .spc = 75,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Gloom,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 65,
        .def = 70,
        .spe = 40,
        .spc = 85,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Vileplume,
    .stats = Stats(u8){
        .hp = 75,
        .atk = 80,
        .def = 85,
        .spe = 50,
        .spc = 100,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Paras,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 70,
        .def = 55,
        .spe = 25,
        .spc = 55,
    },
    .types = [_]Type{ .Bug, .Grass },
}, Specie{
    .id = .Parasect,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 95,
        .def = 80,
        .spe = 30,
        .spc = 80,
    },
    .types = [_]Type{ .Bug, .Grass },
}, Specie{
    .id = .Venonat,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 55,
        .def = 50,
        .spe = 45,
        .spc = 40,
    },
    .types = [_]Type{ .Bug, .Poison },
}, Specie{
    .id = .Venomoth,
    .stats = Stats(u8){
        .hp = 70,
        .atk = 65,
        .def = 60,
        .spe = 90,
        .spc = 90,
    },
    .types = [_]Type{ .Bug, .Poison },
}, Specie{
    .id = .Diglett,
    .stats = Stats(u8){
        .hp = 10,
        .atk = 55,
        .def = 25,
        .spe = 95,
        .spc = 45,
    },
    .types = [_]Type{ .Ground, .Ground },
}, Specie{
    .id = .Dugtrio,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 80,
        .def = 50,
        .spe = 120,
        .spc = 70,
    },
    .types = [_]Type{ .Ground, .Ground },
}, Specie{
    .id = .Meowth,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 45,
        .def = 35,
        .spe = 90,
        .spc = 40,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Persian,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 70,
        .def = 60,
        .spe = 115,
        .spc = 65,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Psyduck,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 52,
        .def = 48,
        .spe = 55,
        .spc = 50,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Golduck,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 82,
        .def = 78,
        .spe = 85,
        .spc = 80,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Mankey,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 80,
        .def = 35,
        .spe = 70,
        .spc = 35,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Primeape,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 105,
        .def = 60,
        .spe = 95,
        .spc = 60,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Growlithe,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 70,
        .def = 45,
        .spe = 60,
        .spc = 50,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Arcanine,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 110,
        .def = 80,
        .spe = 95,
        .spc = 80,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Poliwag,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 50,
        .def = 40,
        .spe = 90,
        .spc = 40,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Poliwhirl,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 65,
        .def = 65,
        .spe = 90,
        .spc = 50,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Poliwrath,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 85,
        .def = 95,
        .spe = 70,
        .spc = 70,
    },
    .types = [_]Type{ .Water, .Fighting },
}, Specie{
    .id = .Abra,
    .stats = Stats(u8){
        .hp = 25,
        .atk = 20,
        .def = 15,
        .spe = 90,
        .spc = 105,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Kadabra,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 35,
        .def = 30,
        .spe = 105,
        .spc = 120,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Alakazam,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 50,
        .def = 45,
        .spe = 120,
        .spc = 135,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Machop,
    .stats = Stats(u8){
        .hp = 70,
        .atk = 80,
        .def = 50,
        .spe = 35,
        .spc = 35,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Machoke,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 100,
        .def = 70,
        .spe = 45,
        .spc = 50,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Machamp,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 130,
        .def = 80,
        .spe = 55,
        .spc = 65,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Bellsprout,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 75,
        .def = 35,
        .spe = 40,
        .spc = 70,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Weepinbell,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 90,
        .def = 50,
        .spe = 55,
        .spc = 85,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Victreebel,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 105,
        .def = 65,
        .spe = 70,
        .spc = 100,
    },
    .types = [_]Type{ .Grass, .Poison },
}, Specie{
    .id = .Tentacool,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 40,
        .def = 35,
        .spe = 70,
        .spc = 100,
    },
    .types = [_]Type{ .Water, .Poison },
}, Specie{
    .id = .Tentacruel,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 70,
        .def = 65,
        .spe = 100,
        .spc = 120,
    },
    .types = [_]Type{ .Water, .Poison },
}, Specie{
    .id = .Geodude,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 80,
        .def = 100,
        .spe = 20,
        .spc = 30,
    },
    .types = [_]Type{ .Rock, .Ground },
}, Specie{
    .id = .Graveler,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 95,
        .def = 115,
        .spe = 35,
        .spc = 45,
    },
    .types = [_]Type{ .Rock, .Ground },
}, Specie{
    .id = .Golem,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 110,
        .def = 130,
        .spe = 45,
        .spc = 55,
    },
    .types = [_]Type{ .Rock, .Ground },
}, Specie{
    .id = .Ponyta,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 85,
        .def = 55,
        .spe = 90,
        .spc = 65,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Rapidash,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 100,
        .def = 70,
        .spe = 105,
        .spc = 80,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Slowpoke,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 65,
        .def = 65,
        .spe = 15,
        .spc = 40,
    },
    .types = [_]Type{ .Water, .Psychic },
}, Specie{
    .id = .Slowbro,
    .stats = Stats(u8){
        .hp = 95,
        .atk = 75,
        .def = 110,
        .spe = 30,
        .spc = 80,
    },
    .types = [_]Type{ .Water, .Psychic },
}, Specie{
    .id = .Magnemite,
    .stats = Stats(u8){
        .hp = 25,
        .atk = 35,
        .def = 70,
        .spe = 45,
        .spc = 95,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Magneton,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 60,
        .def = 95,
        .spe = 70,
        .spc = 120,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Farfetchd,
    .stats = Stats(u8){
        .hp = 52,
        .atk = 65,
        .def = 55,
        .spe = 60,
        .spc = 58,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Doduo,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 85,
        .def = 45,
        .spe = 75,
        .spc = 35,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Dodrio,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 110,
        .def = 70,
        .spe = 100,
        .spc = 60,
    },
    .types = [_]Type{ .Normal, .Flying },
}, Specie{
    .id = .Seel,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 45,
        .def = 55,
        .spe = 45,
        .spc = 70,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Dewgong,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 70,
        .def = 80,
        .spe = 70,
        .spc = 95,
    },
    .types = [_]Type{ .Water, .Ice },
}, Specie{
    .id = .Grimer,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 80,
        .def = 50,
        .spe = 25,
        .spc = 40,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Muk,
    .stats = Stats(u8){
        .hp = 105,
        .atk = 105,
        .def = 75,
        .spe = 50,
        .spc = 65,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Shellder,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 65,
        .def = 100,
        .spe = 40,
        .spc = 45,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Cloyster,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 95,
        .def = 180,
        .spe = 70,
        .spc = 85,
    },
    .types = [_]Type{ .Water, .Ice },
}, Specie{
    .id = .Gastly,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 35,
        .def = 30,
        .spe = 80,
        .spc = 100,
    },
    .types = [_]Type{ .Ghost, .Poison },
}, Specie{
    .id = .Haunter,
    .stats = Stats(u8){
        .hp = 45,
        .atk = 50,
        .def = 45,
        .spe = 95,
        .spc = 115,
    },
    .types = [_]Type{ .Ghost, .Poison },
}, Specie{
    .id = .Gengar,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 65,
        .def = 60,
        .spe = 110,
        .spc = 130,
    },
    .types = [_]Type{ .Ghost, .Poison },
}, Specie{
    .id = .Onix,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 45,
        .def = 160,
        .spe = 70,
        .spc = 30,
    },
    .types = [_]Type{ .Rock, .Ground },
}, Specie{
    .id = .Drowzee,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 48,
        .def = 45,
        .spe = 42,
        .spc = 90,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Hypno,
    .stats = Stats(u8){
        .hp = 85,
        .atk = 73,
        .def = 70,
        .spe = 67,
        .spc = 115,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Krabby,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 105,
        .def = 90,
        .spe = 50,
        .spc = 25,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Kingler,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 130,
        .def = 115,
        .spe = 75,
        .spc = 50,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Voltorb,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 30,
        .def = 50,
        .spe = 100,
        .spc = 55,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Electrode,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 50,
        .def = 70,
        .spe = 140,
        .spc = 80,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Exeggcute,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 40,
        .def = 80,
        .spe = 40,
        .spc = 60,
    },
    .types = [_]Type{ .Grass, .Psychic },
}, Specie{
    .id = .Exeggutor,
    .stats = Stats(u8){
        .hp = 95,
        .atk = 95,
        .def = 85,
        .spe = 55,
        .spc = 125,
    },
    .types = [_]Type{ .Grass, .Psychic },
}, Specie{
    .id = .Cubone,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 50,
        .def = 95,
        .spe = 35,
        .spc = 40,
    },
    .types = [_]Type{ .Ground, .Ground },
}, Specie{
    .id = .Marowak,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 80,
        .def = 110,
        .spe = 45,
        .spc = 50,
    },
    .types = [_]Type{ .Ground, .Ground },
}, Specie{
    .id = .Hitmonlee,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 120,
        .def = 53,
        .spe = 87,
        .spc = 35,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Hitmonchan,
    .stats = Stats(u8){
        .hp = 50,
        .atk = 105,
        .def = 79,
        .spe = 76,
        .spc = 35,
    },
    .types = [_]Type{ .Fighting, .Fighting },
}, Specie{
    .id = .Lickitung,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 55,
        .def = 75,
        .spe = 30,
        .spc = 60,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Koffing,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 65,
        .def = 95,
        .spe = 35,
        .spc = 60,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Weezing,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 90,
        .def = 120,
        .spe = 60,
        .spc = 85,
    },
    .types = [_]Type{ .Poison, .Poison },
}, Specie{
    .id = .Rhyhorn,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 85,
        .def = 95,
        .spe = 25,
        .spc = 30,
    },
    .types = [_]Type{ .Ground, .Rock },
}, Specie{
    .id = .Rhydon,
    .stats = Stats(u8){
        .hp = 105,
        .atk = 130,
        .def = 120,
        .spe = 40,
        .spc = 45,
    },
    .types = [_]Type{ .Ground, .Rock },
}, Specie{
    .id = .Chansey,
    .stats = Stats(u8){
        .hp = 250,
        .atk = 5,
        .def = 5,
        .spe = 50,
        .spc = 105,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Tangela,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 55,
        .def = 115,
        .spe = 60,
        .spc = 100,
    },
    .types = [_]Type{ .Grass, .Grass },
}, Specie{
    .id = .Kangaskhan,
    .stats = Stats(u8){
        .hp = 105,
        .atk = 95,
        .def = 80,
        .spe = 90,
        .spc = 40,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Horsea,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 40,
        .def = 70,
        .spe = 60,
        .spc = 70,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Seadra,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 65,
        .def = 95,
        .spe = 85,
        .spc = 95,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Goldeen,
    .stats = Stats(u8){
        .hp = 45,
        .atk = 67,
        .def = 60,
        .spe = 63,
        .spc = 50,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Seaking,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 92,
        .def = 65,
        .spe = 68,
        .spc = 80,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Staryu,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 45,
        .def = 55,
        .spe = 85,
        .spc = 70,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Starmie,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 75,
        .def = 85,
        .spe = 115,
        .spc = 100,
    },
    .types = [_]Type{ .Water, .Psychic },
}, Specie{
    .id = .MrMime,
    .stats = Stats(u8){
        .hp = 40,
        .atk = 45,
        .def = 65,
        .spe = 90,
        .spc = 100,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Scyther,
    .stats = Stats(u8){
        .hp = 70,
        .atk = 110,
        .def = 80,
        .spe = 105,
        .spc = 55,
    },
    .types = [_]Type{ .Bug, .Flying },
}, Specie{
    .id = .Jynx,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 50,
        .def = 35,
        .spe = 95,
        .spc = 95,
    },
    .types = [_]Type{ .Ice, .Psychic },
}, Specie{
    .id = .Electabuzz,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 83,
        .def = 57,
        .spe = 105,
        .spc = 85,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Magmar,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 95,
        .def = 57,
        .spe = 93,
        .spc = 85,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Pinsir,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 125,
        .def = 100,
        .spe = 85,
        .spc = 55,
    },
    .types = [_]Type{ .Bug, .Bug },
}, Specie{
    .id = .Tauros,
    .stats = Stats(u8){
        .hp = 75,
        .atk = 100,
        .def = 95,
        .spe = 110,
        .spc = 70,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Magikarp,
    .stats = Stats(u8){
        .hp = 20,
        .atk = 10,
        .def = 55,
        .spe = 80,
        .spc = 20,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Gyarados,
    .stats = Stats(u8){
        .hp = 95,
        .atk = 125,
        .def = 79,
        .spe = 81,
        .spc = 100,
    },
    .types = [_]Type{ .Water, .Flying },
}, Specie{
    .id = .Lapras,
    .stats = Stats(u8){
        .hp = 130,
        .atk = 85,
        .def = 80,
        .spe = 60,
        .spc = 95,
    },
    .types = [_]Type{ .Water, .Ice },
}, Specie{
    .id = .Ditto,
    .stats = Stats(u8){
        .hp = 48,
        .atk = 48,
        .def = 48,
        .spe = 48,
        .spc = 48,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Eevee,
    .stats = Stats(u8){
        .hp = 55,
        .atk = 55,
        .def = 50,
        .spe = 55,
        .spc = 65,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Vaporeon,
    .stats = Stats(u8){
        .hp = 130,
        .atk = 65,
        .def = 60,
        .spe = 65,
        .spc = 110,
    },
    .types = [_]Type{ .Water, .Water },
}, Specie{
    .id = .Jolteon,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 65,
        .def = 60,
        .spe = 130,
        .spc = 110,
    },
    .types = [_]Type{ .Electric, .Electric },
}, Specie{
    .id = .Flareon,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 130,
        .def = 60,
        .spe = 65,
        .spc = 110,
    },
    .types = [_]Type{ .Fire, .Fire },
}, Specie{
    .id = .Porygon,
    .stats = Stats(u8){
        .hp = 65,
        .atk = 60,
        .def = 70,
        .spe = 40,
        .spc = 75,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Omanyte,
    .stats = Stats(u8){
        .hp = 35,
        .atk = 40,
        .def = 100,
        .spe = 35,
        .spc = 90,
    },
    .types = [_]Type{ .Rock, .Water },
}, Specie{
    .id = .Omastar,
    .stats = Stats(u8){
        .hp = 70,
        .atk = 60,
        .def = 125,
        .spe = 55,
        .spc = 115,
    },
    .types = [_]Type{ .Rock, .Water },
}, Specie{
    .id = .Kabuto,
    .stats = Stats(u8){
        .hp = 30,
        .atk = 80,
        .def = 90,
        .spe = 55,
        .spc = 45,
    },
    .types = [_]Type{ .Rock, .Water },
}, Specie{
    .id = .Kabutops,
    .stats = Stats(u8){
        .hp = 60,
        .atk = 115,
        .def = 105,
        .spe = 80,
        .spc = 70,
    },
    .types = [_]Type{ .Rock, .Water },
}, Specie{
    .id = .Aerodactyl,
    .stats = Stats(u8){
        .hp = 80,
        .atk = 105,
        .def = 65,
        .spe = 130,
        .spc = 60,
    },
    .types = [_]Type{ .Rock, .Flying },
}, Specie{
    .id = .Snorlax,
    .stats = Stats(u8){
        .hp = 160,
        .atk = 110,
        .def = 65,
        .spe = 30,
        .spc = 65,
    },
    .types = [_]Type{ .Normal, .Normal },
}, Specie{
    .id = .Articuno,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 85,
        .def = 100,
        .spe = 85,
        .spc = 125,
    },
    .types = [_]Type{ .Ice, .Flying },
}, Specie{
    .id = .Zapdos,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 90,
        .def = 85,
        .spe = 100,
        .spc = 125,
    },
    .types = [_]Type{ .Electric, .Flying },
}, Specie{
    .id = .Moltres,
    .stats = Stats(u8){
        .hp = 90,
        .atk = 100,
        .def = 90,
        .spe = 90,
        .spc = 125,
    },
    .types = [_]Type{ .Fire, .Flying },
}, Specie{
    .id = .Dratini,
    .stats = Stats(u8){
        .hp = 41,
        .atk = 64,
        .def = 45,
        .spe = 50,
        .spc = 50,
    },
    .types = [_]Type{ .Dragon, .Dragon },
}, Specie{
    .id = .Dragonair,
    .stats = Stats(u8){
        .hp = 61,
        .atk = 84,
        .def = 65,
        .spe = 70,
        .spc = 70,
    },
    .types = [_]Type{ .Dragon, .Dragon },
}, Specie{
    .id = .Dragonite,
    .stats = Stats(u8){
        .hp = 91,
        .atk = 134,
        .def = 95,
        .spe = 80,
        .spc = 100,
    },
    .types = [_]Type{ .Dragon, .Flying },
}, Specie{
    .id = .Mewtwo,
    .stats = Stats(u8){
        .hp = 106,
        .atk = 110,
        .def = 90,
        .spe = 130,
        .spc = 154,
    },
    .types = [_]Type{ .Psychic, .Psychic },
}, Specie{
    .id = .Mew,
    .stats = Stats(u8){
        .hp = 100,
        .atk = 100,
        .def = 100,
        .spe = 100,
        .spc = 100,
    },
    .types = [_]Type{ .Psychic, .Psychic },
} };
