//! Code generated by `tools/generate` - manual edits will be overwritten.

const common = @import("../common/data.zig");

const data = @import("data.zig");
const mechanics = @import("mechanics.zig");

const Player = common.Player;
const Result = common.Result;

const Move = data.Move;

const Effects = mechanics.Effects;
const State = mechanics.State;

const checkHit = mechanics.checkHit;
const checkCriticalHit = mechanics.checkCriticalHit;
const calcDamage = mechanics.calcDamage;
const adjustDamage = mechanics.adjustDamage;
const randomizeDamage = mechanics.randomizeDamage;
const applyDamage = mechanics.applyDamage;
const buildRage = mechanics.buildRage;
const rageDamage = mechanics.rageDamage;
const kingsRock = mechanics.kingsRock;
const destinyBond = mechanics.destinyBond;

pub fn doMove(battle: anytype, player: Player, state: *State, options: anytype) !?Result {
    _ = .{ battle, player, options };

    switch (Move.get(state.move).effect) {
        .AlwaysHit, .HighCritical, .Priority, .JumpKick, .None => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .DoubleHit, .MultiHit => {
            // TODO usedmovetext
            // TODO doturn
            // TODO startloop
            try checkHit(battle, player, state, options);
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO cleartext
            // TODO supereffectivelooptext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            // TODO endloop
            try kingsRock(battle, player, state, options);
        },
        .PayDay => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.payDay(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .BurnChance => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.burnChance(battle, player, state, options);
        },
        .FreezeChance => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.freezeChance(battle, player, state, options);
        },
        .ParalyzeChance => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.paralyzeChance(battle, player, state, options);
        },
        .OHKO => {
            // TODO usedmovetext
            // TODO doturn
            try adjustDamage(battle, player, state, options);
            try Effects.ohko(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
        },
        .RazorWind => {
            // TODO checkcharge
            // TODO doturn
            // TODO charge
            // TODO usedmovetext
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Gust => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO doubleflyingdamage
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
        },
        .ForceSwitch => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.forceSwitch(battle, player, state, options);
        },
        .FlyDig => {
            // TODO checkcharge
            // TODO doturn
            // TODO charge
            // TODO usedmovetext
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Binding => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.binding(battle, player, state, options);
        },
        .Stomp => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO doubleminimizedamage
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.flinchChance(battle, player, state, options);
        },
        .FlinchChance => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.flinchChance(battle, player, state, options);
        },
        .Recoil => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.recoil(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Thrashing => {
            // TODO checkrampage
            // TODO doturn
            // TODO rampage
            // TODO usedmovetext
            try checkHit(battle, player, state, options);
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .PoisonChance => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.poisonChance(battle, player, state, options);
        },
        .Twineedle => {
            // TODO usedmovetext
            // TODO doturn
            // TODO startloop
            try checkHit(battle, player, state, options);
            // TODO effectchance
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO cleartext
            // TODO supereffectivelooptext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            // TODO endloop
            try kingsRock(battle, player, state, options);
            try Effects.poisonChance(battle, player, state, options);
        },
        .Sleep => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            // TODO checksafeguard
            try Effects.sleep(battle, player, state, options);
        },
        .Confusion => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            // TODO checksafeguard
            try Effects.confusion(battle, player, state, options);
        },
        .SuperFang, .LevelDamage, .Psywave, .FixedDamage => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.fixedDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO resettypematchup
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Disable => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.disable(battle, player, state, options);
        },
        .Mist => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.mist(battle, player, state, options);
        },
        .ConfusionChance => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.confusionChance(battle, player, state, options);
        },
        .HyperBeam => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.hyperBeam(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
        },
        .Counter => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.counter(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .DreamEater, .DrainHP => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.drainHP(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .LeechSeed => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.leechSeed(battle, player, state, options);
        },
        .Solarbeam => {
            // TODO checkcharge
            // TODO doturn
            try Effects.solarBeam(battle, player, state, options);
            // TODO charge
            // TODO usedmovetext
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Toxic, .Poison => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try adjustDamage(battle, player, state, options);
            // TODO checksafeguard
            try Effects.poison(battle, player, state, options);
        },
        .Paralyze => {
            // TODO usedmovetext
            // TODO doturn
            try adjustDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO checksafeguard
            try Effects.paralyze(battle, player, state, options);
        },
        .Thunder => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            // TODO thunderaccuracy
            try checkHit(battle, player, state, options);
            // TODO effectchance
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.paralyzeChance(battle, player, state, options);
        },
        .Earthquake => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO doubleundergrounddamage
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
        },
        .Rage => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            try rageDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO failuretext
            try Effects.rage(battle, player, state, options);
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Teleport => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.teleport(battle, player, state, options);
        },
        .Mimic => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.mimic(battle, player, state, options);
        },
        .Heal => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.heal(battle, player, state, options);
        },
        .DefenseCurl => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.boost(battle, player, state, options);
            try Effects.defenseCurl(battle, player, state, options);
        },
        .Haze => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.haze(battle, player, state, options);
        },
        .LightScreen, .Reflect => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.screens(battle, player, state, options);
        },
        .FocusEnergy => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.focusEnergy(battle, player, state, options);
        },
        .Bide => {
            // TODO storeenergy
            // TODO doturn
            // TODO usedmovetext
            // TODO unleashenergy
            // TODO resettypematchup
            try checkHit(battle, player, state, options);
            // TODO bidefailtext
            try applyDamage(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Metronome => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.metronome(battle, player, state, options);
        },
        .MirrorMove => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.mirrorMove(battle, player, state, options);
        },
        .Explode => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            try Effects.explode(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .SkullBash => {
            // TODO checkcharge
            // TODO doturn
            // TODO charge
            // TODO usedmovetext
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
            // TODO endturn
            try Effects.boost(battle, player, state, options);
        },
        .SkyAttack => {
            // TODO checkcharge
            // TODO doturn
            // TODO charge
            // TODO usedmovetext
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.flinchChance(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Transform => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.transform(battle, player, state, options);
        },
        .Splash => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.splash(battle, player, state, options);
        },
        .Conversion => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.conversion(battle, player, state, options);
        },
        .TriAttack => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.triAttack(battle, player, state, options);
        },
        .Substitute => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.substitute(battle, player, state, options);
        },
        .Sketch => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.sketch(battle, player, state, options);
        },
        .TripleKick => {
            // TODO usedmovetext
            // TODO doturn
            // TODO startloop
            try checkHit(battle, player, state, options);
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try Effects.tripleKick(battle, player, state, options);
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO cleartext
            // TODO supereffectivelooptext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            // TODO kickcounter
            // TODO endloop
            try kingsRock(battle, player, state, options);
        },
        .Thief => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.thief(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .MeanLook => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.meanLook(battle, player, state, options);
        },
        .LockOn => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.lockOn(battle, player, state, options);
        },
        .Nightmare => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.nightmare(battle, player, state, options);
        },
        .Snore => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            try Effects.snore(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.flinchChance(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Curse => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.curse(battle, player, state, options);
        },
        .Reversal => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.fixedDamage(battle, player, state, options);
            try adjustDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Conversion2 => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.conversion2(battle, player, state, options);
        },
        .Spite => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.spite(battle, player, state, options);
        },
        .Endure, .Protect => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.protect(battle, player, state, options);
        },
        .BellyDrum => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.bellyDrum(battle, player, state, options);
        },
        .Spikes => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.spikes(battle, player, state, options);
        },
        .Foresight => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.foresight(battle, player, state, options);
        },
        .DestinyBond => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.destinyBond(battle, player, state, options);
        },
        .PerishSong => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.perishSong(battle, player, state, options);
        },
        .Sandstorm => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.sandstorm(battle, player, state, options);
        },
        .Rollout => {
            // TODO checkcurl
            // TODO doturn
            // TODO usedmovetext
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO rolloutpower
            try randomizeDamage(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .FalseSwipe => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try Effects.falseSwipe(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Swagger => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            // TODO switchturn
            // TODO attackup2
            // TODO switchturn
            // TODO failuretext
            // TODO switchturn
            // TODO switchturn
            try Effects.confusionChance(battle, player, state, options);
        },
        .FuryCutter => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            try Effects.furyCutter(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Attract => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.attract(battle, player, state, options);
        },
        .SleepTalk => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.sleepTalk(battle, player, state, options);
        },
        .HealBell => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.healBell(battle, player, state, options);
        },
        .Frustration, .Return => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            try Effects.happiness(battle, player, state, options);
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Present => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            try Effects.present(battle, player, state, options);
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Safeguard => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.safeguard(battle, player, state, options);
        },
        .PainSplit => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.painSplit(battle, player, state, options);
        },
        .FlameWheel, .SacredFire => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.defrost(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.burnChance(battle, player, state, options);
        },
        .Magnitude => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO getmagnitude
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO doubleundergrounddamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .BatonPass => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.batonPass(battle, player, state, options);
        },
        .Encore => {
            // TODO usedmovetext
            // TODO doturn
            try checkHit(battle, player, state, options);
            try Effects.encore(battle, player, state, options);
        },
        .Pursuit => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try Effects.pursuit(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .RapidSpin => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            try Effects.rapidSpin(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .MorningSun, .Synthesis, .Moonlight => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.weatherHeal(battle, player, state, options);
        },
        .HiddenPower => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            try Effects.hiddenPower(battle, player, state, options);
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .Twister => {
            // TODO usedmovetext
            // TODO doturn
            try checkCriticalHit(battle, player, state, options);
            // TODO damagestats
            // TODO damagecalc
            try adjustDamage(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            // TODO doubleflyingdamage
            try checkHit(battle, player, state, options);
            // TODO effectchance
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try Effects.flinchChance(battle, player, state, options);
        },
        .RainDance => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.rainDance(battle, player, state, options);
        },
        .SunnyDay => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.sunnyDay(battle, player, state, options);
        },
        .MirrorCoat => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.mirrorCoat(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            try kingsRock(battle, player, state, options);
        },
        .PsychUp => {
            // TODO usedmovetext
            // TODO doturn
            try Effects.psychUp(battle, player, state, options);
        },
        .FutureSight => {
            // TODO checkfuturesight
            // TODO usedmovetext
            // TODO doturn
            // TODO damagestats
            // TODO damagecalc
            try Effects.futureSight(battle, player, state, options);
            try randomizeDamage(battle, player, state, options);
            try checkHit(battle, player, state, options);
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
        },
        .BeatUp => {
            // TODO usedmovetext
            // TODO movedelay
            // TODO doturn
            // TODO startloop
            try checkHit(battle, player, state, options);
            try checkCriticalHit(battle, player, state, options);
            try Effects.beatUp(battle, player, state, options);
            // TODO damagecalc
            try randomizeDamage(battle, player, state, options);
            // TODO clearmissdamage
            // TODO failuretext
            try applyDamage(battle, player, state, options);
            // TODO criticaltext
            // TODO cleartext
            // TODO supereffectivetext
            _ = try destinyBond(battle, player, state, options);
            try buildRage(battle, player, state, options);
            // TODO endloop
            // TODO beatupfailtext
            try kingsRock(battle, player, state, options);
        },
        // zig fmt: off
        .AllStatUpChance, .AttackUp1, .AttackUp2, .AttackUpChance, .DefenseUp1,
        .DefenseUp2, .DefenseUpChance, .EvasionUp1, .SpAtkUp1, .SpDefUp2, .SpeedUp2 => {}, // TODO
        // zig fmt: on
        // zig fmt: off
        .AccuracyDown1, .AccuracyDownChance, .AttackDown1, .AttackDown2,
        .AttackDownChance, .DefenseDown1, .DefenseDown2, .DefenseDownChance,
        .EvasionDown1, .SpDefDownChance, .SpeedDown1, .SpeedDown2, .SpeedDownChance => {}, // TODO
        // zig fmt: on
    }

    return null;
}
