//! Code generated by `tools/generate` - manual edits will be overwritten

const std = @import("std");
const builtin = @import("builtin");
const gen2 = @import("../../gen2/data.zig");

const assert = std.debug.assert;

const Type = gen2.Type;

pub const Move = enum(u8) {
    None,
    Pound,
    KarateChop,
    DoubleSlap,
    CometPunch,
    MegaPunch,
    PayDay,
    FirePunch,
    IcePunch,
    ThunderPunch,
    Scratch,
    ViseGrip,
    Guillotine,
    RazorWind,
    SwordsDance,
    Cut,
    Gust,
    WingAttack,
    Whirlwind,
    Fly,
    Bind,
    Slam,
    VineWhip,
    Stomp,
    DoubleKick,
    MegaKick,
    JumpKick,
    RollingKick,
    SandAttack,
    Headbutt,
    HornAttack,
    FuryAttack,
    HornDrill,
    Tackle,
    BodySlam,
    Wrap,
    TakeDown,
    Thrash,
    DoubleEdge,
    TailWhip,
    PoisonSting,
    Twineedle,
    PinMissile,
    Leer,
    Bite,
    Growl,
    Roar,
    Sing,
    Supersonic,
    SonicBoom,
    Disable,
    Acid,
    Ember,
    Flamethrower,
    Mist,
    WaterGun,
    HydroPump,
    Surf,
    IceBeam,
    Blizzard,
    Psybeam,
    BubbleBeam,
    AuroraBeam,
    HyperBeam,
    Peck,
    DrillPeck,
    Submission,
    LowKick,
    Counter,
    SeismicToss,
    Strength,
    Absorb,
    MegaDrain,
    LeechSeed,
    Growth,
    RazorLeaf,
    SolarBeam,
    PoisonPowder,
    StunSpore,
    SleepPowder,
    PetalDance,
    StringShot,
    DragonRage,
    FireSpin,
    ThunderShock,
    Thunderbolt,
    ThunderWave,
    Thunder,
    RockThrow,
    Earthquake,
    Fissure,
    Dig,
    Toxic,
    Confusion,
    Psychic,
    Hypnosis,
    Meditate,
    Agility,
    QuickAttack,
    Rage,
    Teleport,
    NightShade,
    Mimic,
    Screech,
    DoubleTeam,
    Recover,
    Harden,
    Minimize,
    Smokescreen,
    ConfuseRay,
    Withdraw,
    DefenseCurl,
    Barrier,
    LightScreen,
    Haze,
    Reflect,
    FocusEnergy,
    Bide,
    Metronome,
    MirrorMove,
    SelfDestruct,
    EggBomb,
    Lick,
    Smog,
    Sludge,
    BoneClub,
    FireBlast,
    Waterfall,
    Clamp,
    Swift,
    SkullBash,
    SpikeCannon,
    Constrict,
    Amnesia,
    Kinesis,
    SoftBoiled,
    HighJumpKick,
    Glare,
    DreamEater,
    PoisonGas,
    Barrage,
    LeechLife,
    LovelyKiss,
    SkyAttack,
    Transform,
    Bubble,
    DizzyPunch,
    Spore,
    Flash,
    Psywave,
    Splash,
    AcidArmor,
    Crabhammer,
    Explosion,
    FurySwipes,
    Bonemerang,
    Rest,
    RockSlide,
    HyperFang,
    Sharpen,
    Conversion,
    TriAttack,
    SuperFang,
    Slash,
    Substitute,
    Struggle,
    Sketch,
    TripleKick,
    Thief,
    SpiderWeb,
    MindReader,
    Nightmare,
    FlameWheel,
    Snore,
    Curse,
    Flail,
    Conversion2,
    Aeroblast,
    CottonSpore,
    Reversal,
    Spite,
    PowderSnow,
    Protect,
    MachPunch,
    ScaryFace,
    FeintAttack,
    SweetKiss,
    BellyDrum,
    SludgeBomb,
    MudSlap,
    Octazooka,
    Spikes,
    ZapCannon,
    Foresight,
    DestinyBond,
    PerishSong,
    IcyWind,
    Detect,
    BoneRush,
    LockOn,
    Outrage,
    Sandstorm,
    GigaDrain,
    Endure,
    Charm,
    Rollout,
    FalseSwipe,
    Swagger,
    MilkDrink,
    Spark,
    FuryCutter,
    SteelWing,
    MeanLook,
    Attract,
    SleepTalk,
    HealBell,
    Return,
    Present,
    Frustration,
    Safeguard,
    PainSplit,
    SacredFire,
    Magnitude,
    DynamicPunch,
    Megahorn,
    DragonBreath,
    BatonPass,
    Encore,
    Pursuit,
    RapidSpin,
    SweetScent,
    IronTail,
    MetalClaw,
    VitalThrow,
    MorningSun,
    Synthesis,
    Moonlight,
    HiddenPower,
    CrossChop,
    Twister,
    RainDance,
    SunnyDay,
    Crunch,
    MirrorCoat,
    PsychUp,
    ExtremeSpeed,
    AncientPower,
    ShadowBall,
    FutureSight,
    RockSmash,
    Whirlpool,
    BeatUp,

    pub const Data = packed struct {
        bp: u8,
        accuracy: u8,
        type: Type,
        pp: u4, // pp / 5
        chance: u4 = 0, // chance / 10
        // TODO effect and parameter?

        comptime {
            assert(@sizeOf(Data) == 4);
            // TODO: Safety check workaround for ziglang/zig#2627
            assert(@bitSizeOf(Data) == @sizeOf(Data) * 8);
        }
    };

    const data = [_]Data{
        // Pound
        .{
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        // KarateChop
        .{
            .bp = 50,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        // DoubleSlap
        .{
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        // CometPunch
        .{
            .bp = 18,
            .type = .Normal,
            .accuracy = 85,
            .pp = 3, // * 5 = 15
        },
        // MegaPunch
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        // PayDay
        .{
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // FirePunch
        .{
            .bp = 75,
            .type = .Fire,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        // IcePunch
        .{
            .bp = 75,
            .type = .Ice,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        // ThunderPunch
        .{
            .bp = 75,
            .type = .Electric,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        // Scratch
        .{
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        // ViseGrip
        .{
            .bp = 55,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Guillotine
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 30,
            .pp = 1, // * 5 = 5
        },
        // RazorWind
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        // SwordsDance
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Cut
        .{
            .bp = 50,
            .type = .Normal,
            .accuracy = 95,
            .pp = 6, // * 5 = 30
        },
        // Gust
        .{
            .bp = 40,
            .type = .Flying,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        // WingAttack
        .{
            .bp = 60,
            .type = .Flying,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        // Whirlwind
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Fly
        .{
            .bp = 70,
            .type = .Flying,
            .accuracy = 95,
            .pp = 3, // * 5 = 15
        },
        // Bind
        .{
            .bp = 15,
            .type = .Normal,
            .accuracy = 75,
            .pp = 4, // * 5 = 20
        },
        // Slam
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 75,
            .pp = 4, // * 5 = 20
        },
        // VineWhip
        .{
            .bp = 35,
            .type = .Grass,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Stomp
        .{
            .bp = 65,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        // DoubleKick
        .{
            .bp = 30,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // MegaKick
        .{
            .bp = 120,
            .type = .Normal,
            .accuracy = 75,
            .pp = 1, // * 5 = 5
        },
        // JumpKick
        .{
            .bp = 70,
            .type = .Fighting,
            .accuracy = 95,
            .pp = 5, // * 5 = 25
        },
        // RollingKick
        .{
            .bp = 60,
            .type = .Fighting,
            .accuracy = 85,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        // SandAttack
        .{
            .bp = 0,
            .type = .Ground,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Headbutt
        .{
            .bp = 70,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        // HornAttack
        .{
            .bp = 65,
            .type = .Normal,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        // FuryAttack
        .{
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        // HornDrill
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 30,
            .pp = 1, // * 5 = 5
        },
        // Tackle
        .{
            .bp = 35,
            .type = .Normal,
            .accuracy = 95,
            .pp = 7, // * 5 = 35
        },
        // BodySlam
        .{
            .bp = 85,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        // Wrap
        .{
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        // TakeDown
        .{
            .bp = 90,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        // Thrash
        .{
            .bp = 90,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // DoubleEdge
        .{
            .bp = 120,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // TailWhip
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // PoisonSting
        .{
            .bp = 15,
            .type = .Poison,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
            .chance = 3, // * 10 = 30
        },
        // Twineedle
        .{
            .bp = 25,
            .type = .Bug,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 2, // * 10 = 20
        },
        // PinMissile
        .{
            .bp = 14,
            .type = .Bug,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        // Leer
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Bite
        .{
            .bp = 60,
            .type = .Dark,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 3, // * 10 = 30
        },
        // Growl
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // Roar
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Sing
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 55,
            .pp = 3, // * 5 = 15
        },
        // Supersonic
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 55,
            .pp = 4, // * 5 = 20
        },
        // SonicBoom
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
        },
        // Disable
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 55,
            .pp = 4, // * 5 = 20
        },
        // Acid
        .{
            .bp = 40,
            .type = .Poison,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 1, // * 10 = 10
        },
        // Ember
        .{
            .bp = 40,
            .type = .Fire,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        // Flamethrower
        .{
            .bp = 95,
            .type = .Fire,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        // Mist
        .{
            .bp = 0,
            .type = .Ice,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // WaterGun
        .{
            .bp = 40,
            .type = .Water,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        // HydroPump
        .{
            .bp = 120,
            .type = .Water,
            .accuracy = 80,
            .pp = 1, // * 5 = 5
        },
        // Surf
        .{
            .bp = 95,
            .type = .Water,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // IceBeam
        .{
            .bp = 95,
            .type = .Ice,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 1, // * 10 = 10
        },
        // Blizzard
        .{
            .bp = 120,
            .type = .Ice,
            .accuracy = 70,
            .pp = 1, // * 5 = 5
            .chance = 1, // * 10 = 10
        },
        // Psybeam
        .{
            .bp = 65,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        // BubbleBeam
        .{
            .bp = 65,
            .type = .Water,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        // AuroraBeam
        .{
            .bp = 65,
            .type = .Ice,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        // HyperBeam
        .{
            .bp = 150,
            .type = .Normal,
            .accuracy = 90,
            .pp = 1, // * 5 = 5
        },
        // Peck
        .{
            .bp = 35,
            .type = .Flying,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        // DrillPeck
        .{
            .bp = 80,
            .type = .Flying,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Submission
        .{
            .bp = 80,
            .type = .Fighting,
            .accuracy = 80,
            .pp = 5, // * 5 = 25
        },
        // LowKick
        .{
            .bp = 50,
            .type = .Fighting,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        // Counter
        .{
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // SeismicToss
        .{
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Strength
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Absorb
        .{
            .bp = 20,
            .type = .Grass,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // MegaDrain
        .{
            .bp = 40,
            .type = .Grass,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // LeechSeed
        .{
            .bp = 0,
            .type = .Grass,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        // Growth
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // RazorLeaf
        .{
            .bp = 55,
            .type = .Grass,
            .accuracy = 95,
            .pp = 5, // * 5 = 25
        },
        // SolarBeam
        .{
            .bp = 120,
            .type = .Grass,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // PoisonPowder
        .{
            .bp = 0,
            .type = .Poison,
            .accuracy = 75,
            .pp = 7, // * 5 = 35
        },
        // StunSpore
        .{
            .bp = 0,
            .type = .Grass,
            .accuracy = 75,
            .pp = 6, // * 5 = 30
        },
        // SleepPowder
        .{
            .bp = 0,
            .type = .Grass,
            .accuracy = 75,
            .pp = 3, // * 5 = 15
        },
        // PetalDance
        .{
            .bp = 70,
            .type = .Grass,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // StringShot
        .{
            .bp = 0,
            .type = .Bug,
            .accuracy = 95,
            .pp = 8, // * 5 = 40
        },
        // DragonRage
        .{
            .bp = 0,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // FireSpin
        .{
            .bp = 15,
            .type = .Fire,
            .accuracy = 70,
            .pp = 3, // * 5 = 15
        },
        // ThunderShock
        .{
            .bp = 40,
            .type = .Electric,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 1, // * 10 = 10
        },
        // Thunderbolt
        .{
            .bp = 95,
            .type = .Electric,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        // ThunderWave
        .{
            .bp = 0,
            .type = .Electric,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Thunder
        .{
            .bp = 120,
            .type = .Electric,
            .accuracy = 70,
            .pp = 2, // * 5 = 10
            .chance = 3, // * 10 = 30
        },
        // RockThrow
        .{
            .bp = 50,
            .type = .Rock,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        // Earthquake
        .{
            .bp = 100,
            .type = .Ground,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Fissure
        .{
            .bp = 0,
            .type = .Ground,
            .accuracy = 30,
            .pp = 1, // * 5 = 5
        },
        // Dig
        .{
            .bp = 60,
            .type = .Ground,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Toxic
        .{
            .bp = 0,
            .type = .Poison,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        // Confusion
        .{
            .bp = 50,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        // Psychic
        .{
            .bp = 90,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 1, // * 10 = 10
        },
        // Hypnosis
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 60,
            .pp = 4, // * 5 = 20
        },
        // Meditate
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // Agility
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // QuickAttack
        .{
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Rage
        .{
            .bp = 20,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Teleport
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // NightShade
        .{
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Mimic
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Screech
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 85,
            .pp = 8, // * 5 = 40
        },
        // DoubleTeam
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Recover
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Harden
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Minimize
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Smokescreen
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // ConfuseRay
        .{
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Withdraw
        .{
            .bp = 0,
            .type = .Water,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // DefenseCurl
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // Barrier
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // LightScreen
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Haze
        .{
            .bp = 0,
            .type = .Ice,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Reflect
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // FocusEnergy
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Bide
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Metronome
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // MirrorMove
        .{
            .bp = 0,
            .type = .Flying,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // SelfDestruct
        .{
            .bp = 200,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // EggBomb
        .{
            .bp = 100,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        // Lick
        .{
            .bp = 20,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 3, // * 10 = 30
        },
        // Smog
        .{
            .bp = 20,
            .type = .Poison,
            .accuracy = 70,
            .pp = 4, // * 5 = 20
            .chance = 4, // * 10 = 40
        },
        // Sludge
        .{
            .bp = 65,
            .type = .Poison,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        // BoneClub
        .{
            .bp = 65,
            .type = .Ground,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        // FireBlast
        .{
            .bp = 120,
            .type = .Fire,
            .accuracy = 85,
            .pp = 1, // * 5 = 5
            .chance = 1, // * 10 = 10
        },
        // Waterfall
        .{
            .bp = 80,
            .type = .Water,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Clamp
        .{
            .bp = 35,
            .type = .Water,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        // Swift
        .{
            .bp = 60,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // SkullBash
        .{
            .bp = 100,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // SpikeCannon
        .{
            .bp = 20,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Constrict
        .{
            .bp = 10,
            .type = .Normal,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
            .chance = 1, // * 10 = 10
        },
        // Amnesia
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Kinesis
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 80,
            .pp = 3, // * 5 = 15
        },
        // SoftBoiled
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // HighJumpKick
        .{
            .bp = 85,
            .type = .Fighting,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
        },
        // Glare
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 75,
            .pp = 6, // * 5 = 30
        },
        // DreamEater
        .{
            .bp = 100,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // PoisonGas
        .{
            .bp = 0,
            .type = .Poison,
            .accuracy = 55,
            .pp = 8, // * 5 = 40
        },
        // Barrage
        .{
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        // LeechLife
        .{
            .bp = 20,
            .type = .Bug,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // LovelyKiss
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        // SkyAttack
        .{
            .bp = 140,
            .type = .Flying,
            .accuracy = 90,
            .pp = 1, // * 5 = 5
        },
        // Transform
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Bubble
        .{
            .bp = 20,
            .type = .Water,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 1, // * 10 = 10
        },
        // DizzyPunch
        .{
            .bp = 70,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 2, // * 10 = 20
        },
        // Spore
        .{
            .bp = 0,
            .type = .Grass,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Flash
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 70,
            .pp = 4, // * 5 = 20
        },
        // Psywave
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 80,
            .pp = 3, // * 5 = 15
        },
        // Splash
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // AcidArmor
        .{
            .bp = 0,
            .type = .Poison,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // Crabhammer
        .{
            .bp = 90,
            .type = .Water,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        // Explosion
        .{
            .bp = 250,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // FurySwipes
        .{
            .bp = 18,
            .type = .Normal,
            .accuracy = 80,
            .pp = 3, // * 5 = 15
        },
        // Bonemerang
        .{
            .bp = 50,
            .type = .Ground,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        // Rest
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // RockSlide
        .{
            .bp = 75,
            .type = .Rock,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
            .chance = 3, // * 10 = 30
        },
        // HyperFang
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        // Sharpen
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Conversion
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // TriAttack
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 2, // * 10 = 20
        },
        // SuperFang
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        // Slash
        .{
            .bp = 70,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Substitute
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Struggle
        .{
            .bp = 50,
            .type = .Normal,
            .accuracy = 100,
            .pp = 0, // = 1
        },
        // Sketch
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 0, // = 1
        },
        // TripleKick
        .{
            .bp = 10,
            .type = .Fighting,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        // Thief
        .{
            .bp = 40,
            .type = .Dark,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 10, // * 10 = 100
        },
        // SpiderWeb
        .{
            .bp = 0,
            .type = .Bug,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // MindReader
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Nightmare
        .{
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // FlameWheel
        .{
            .bp = 60,
            .type = .Fire,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        // Snore
        .{
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        // Curse
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Flail
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Conversion2
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // Aeroblast
        .{
            .bp = 100,
            .type = .Flying,
            .accuracy = 95,
            .pp = 1, // * 5 = 5
        },
        // CottonSpore
        .{
            .bp = 0,
            .type = .Grass,
            .accuracy = 85,
            .pp = 8, // * 5 = 40
        },
        // Reversal
        .{
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Spite
        .{
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // PowderSnow
        .{
            .bp = 40,
            .type = .Ice,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        // Protect
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // MachPunch
        .{
            .bp = 40,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // ScaryFace
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        // FeintAttack
        .{
            .bp = 60,
            .type = .Dark,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // SweetKiss
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        // BellyDrum
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // SludgeBomb
        .{
            .bp = 90,
            .type = .Poison,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 3, // * 10 = 30
        },
        // MudSlap
        .{
            .bp = 20,
            .type = .Ground,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 10, // * 10 = 100
        },
        // Octazooka
        .{
            .bp = 65,
            .type = .Water,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
            .chance = 5, // * 10 = 50
        },
        // Spikes
        .{
            .bp = 0,
            .type = .Ground,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // ZapCannon
        .{
            .bp = 100,
            .type = .Electric,
            .accuracy = 50,
            .pp = 1, // * 5 = 5
            .chance = 10, // * 10 = 100
        },
        // Foresight
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // DestinyBond
        .{
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // PerishSong
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // IcyWind
        .{
            .bp = 55,
            .type = .Ice,
            .accuracy = 95,
            .pp = 3, // * 5 = 15
            .chance = 10, // * 10 = 100
        },
        // Detect
        .{
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // BoneRush
        .{
            .bp = 25,
            .type = .Ground,
            .accuracy = 80,
            .pp = 2, // * 5 = 10
        },
        // LockOn
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Outrage
        .{
            .bp = 90,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // Sandstorm
        .{
            .bp = 0,
            .type = .Rock,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // GigaDrain
        .{
            .bp = 60,
            .type = .Grass,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Endure
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Charm
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Rollout
        .{
            .bp = 30,
            .type = .Rock,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
        },
        // FalseSwipe
        .{
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // Swagger
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        // MilkDrink
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // Spark
        .{
            .bp = 65,
            .type = .Electric,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        // FuryCutter
        .{
            .bp = 10,
            .type = .Bug,
            .accuracy = 95,
            .pp = 4, // * 5 = 20
        },
        // SteelWing
        .{
            .bp = 70,
            .type = .Steel,
            .accuracy = 90,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        // MeanLook
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Attract
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // SleepTalk
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // HealBell
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Return
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Present
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        // Frustration
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // Safeguard
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        // PainSplit
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // SacredFire
        .{
            .bp = 100,
            .type = .Fire,
            .accuracy = 95,
            .pp = 1, // * 5 = 5
            .chance = 5, // * 10 = 50
        },
        // Magnitude
        .{
            .bp = 0,
            .type = .Ground,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        // DynamicPunch
        .{
            .bp = 100,
            .type = .Fighting,
            .accuracy = 50,
            .pp = 1, // * 5 = 5
            .chance = 10, // * 10 = 100
        },
        // Megahorn
        .{
            .bp = 120,
            .type = .Bug,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        // DragonBreath
        .{
            .bp = 60,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        // BatonPass
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // Encore
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Pursuit
        .{
            .bp = 40,
            .type = .Dark,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // RapidSpin
        .{
            .bp = 20,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        // SweetScent
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // IronTail
        .{
            .bp = 100,
            .type = .Steel,
            .accuracy = 75,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        // MetalClaw
        .{
            .bp = 50,
            .type = .Steel,
            .accuracy = 95,
            .pp = 7, // * 5 = 35
            .chance = 1, // * 10 = 10
        },
        // VitalThrow
        .{
            .bp = 70,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // MorningSun
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Synthesis
        .{
            .bp = 0,
            .type = .Grass,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Moonlight
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // HiddenPower
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        // CrossChop
        .{
            .bp = 100,
            .type = .Fighting,
            .accuracy = 80,
            .pp = 1, // * 5 = 5
        },
        // Twister
        .{
            .bp = 40,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 2, // * 10 = 20
        },
        // RainDance
        .{
            .bp = 0,
            .type = .Water,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // SunnyDay
        .{
            .bp = 0,
            .type = .Fire,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // Crunch
        .{
            .bp = 80,
            .type = .Dark,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 2, // * 10 = 20
        },
        // MirrorCoat
        .{
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        // PsychUp
        .{
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        // ExtremeSpeed
        .{
            .bp = 80,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        // AncientPower
        .{
            .bp = 60,
            .type = .Rock,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
            .chance = 1, // * 10 = 10
        },
        // ShadowBall
        .{
            .bp = 80,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 2, // * 10 = 20
        },
        // FutureSight
        .{
            .bp = 80,
            .type = .Psychic,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        // RockSmash
        .{
            .bp = 20,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 5, // * 10 = 50
        },
        // Whirlpool
        .{
            .bp = 15,
            .type = .Water,
            .accuracy = 70,
            .pp = 3, // * 5 = 15
        },
        // BeatUp
        .{
            .bp = 10,
            .type = .Dark,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
    };

    comptime {
        assert(@sizeOf(Move) == 1);
        assert(@sizeOf(@TypeOf(data)) == 1004);
    }

    pub fn get(id: Move) Data {
        assert(id != .None);
        return data[@enumToInt(id) - 1];
    }

    // @test-only
    pub fn pp(id: Move) u8 {
        assert(builtin.is_test);
        return Move.get(id).pp * 5;
    }
};
