//! Code generated by `tools/generate` - manual edits will be overwritten

const std = @import("std");
const gen2 = @import("../../gen2/data.zig");

const assert = std.debug.assert;

const Move = gen2.Move;
const Type = gen2.Type;

pub const Moves = enum(u8) {
    None,
    Pound,
    KarateChop,
    DoubleSlap,
    CometPunch,
    MegaPunch,
    PayDay,
    FirePunch,
    IcePunch,
    ThunderPunch,
    Scratch,
    ViseGrip,
    Guillotine,
    RazorWind,
    SwordsDance,
    Cut,
    Gust,
    WingAttack,
    Whirlwind,
    Fly,
    Bind,
    Slam,
    VineWhip,
    Stomp,
    DoubleKick,
    MegaKick,
    JumpKick,
    RollingKick,
    SandAttack,
    Headbutt,
    HornAttack,
    FuryAttack,
    HornDrill,
    Tackle,
    BodySlam,
    Wrap,
    TakeDown,
    Thrash,
    DoubleEdge,
    TailWhip,
    PoisonSting,
    Twineedle,
    PinMissile,
    Leer,
    Bite,
    Growl,
    Roar,
    Sing,
    Supersonic,
    SonicBoom,
    Disable,
    Acid,
    Ember,
    Flamethrower,
    Mist,
    WaterGun,
    HydroPump,
    Surf,
    IceBeam,
    Blizzard,
    Psybeam,
    BubbleBeam,
    AuroraBeam,
    HyperBeam,
    Peck,
    DrillPeck,
    Submission,
    LowKick,
    Counter,
    SeismicToss,
    Strength,
    Absorb,
    MegaDrain,
    LeechSeed,
    Growth,
    RazorLeaf,
    SolarBeam,
    PoisonPowder,
    StunSpore,
    SleepPowder,
    PetalDance,
    StringShot,
    DragonRage,
    FireSpin,
    ThunderShock,
    Thunderbolt,
    ThunderWave,
    Thunder,
    RockThrow,
    Earthquake,
    Fissure,
    Dig,
    Toxic,
    Confusion,
    Psychic,
    Hypnosis,
    Meditate,
    Agility,
    QuickAttack,
    Rage,
    Teleport,
    NightShade,
    Mimic,
    Screech,
    DoubleTeam,
    Recover,
    Harden,
    Minimize,
    Smokescreen,
    ConfuseRay,
    Withdraw,
    DefenseCurl,
    Barrier,
    LightScreen,
    Haze,
    Reflect,
    FocusEnergy,
    Bide,
    Metronome,
    MirrorMove,
    SelfDestruct,
    EggBomb,
    Lick,
    Smog,
    Sludge,
    BoneClub,
    FireBlast,
    Waterfall,
    Clamp,
    Swift,
    SkullBash,
    SpikeCannon,
    Constrict,
    Amnesia,
    Kinesis,
    SoftBoiled,
    HighJumpKick,
    Glare,
    DreamEater,
    PoisonGas,
    Barrage,
    LeechLife,
    LovelyKiss,
    SkyAttack,
    Transform,
    Bubble,
    DizzyPunch,
    Spore,
    Flash,
    Psywave,
    Splash,
    AcidArmor,
    Crabhammer,
    Explosion,
    FurySwipes,
    Bonemerang,
    Rest,
    RockSlide,
    HyperFang,
    Sharpen,
    Conversion,
    TriAttack,
    SuperFang,
    Slash,
    Substitute,
    Struggle,
    Sketch,
    TripleKick,
    Thief,
    SpiderWeb,
    MindReader,
    Nightmare,
    FlameWheel,
    Snore,
    Curse,
    Flail,
    Conversion2,
    Aeroblast,
    CottonSpore,
    Reversal,
    Spite,
    PowderSnow,
    Protect,
    MachPunch,
    ScaryFace,
    FeintAttack,
    SweetKiss,
    BellyDrum,
    SludgeBomb,
    MudSlap,
    Octazooka,
    Spikes,
    ZapCannon,
    Foresight,
    DestinyBond,
    PerishSong,
    IcyWind,
    Detect,
    BoneRush,
    LockOn,
    Outrage,
    Sandstorm,
    GigaDrain,
    Endure,
    Charm,
    Rollout,
    FalseSwipe,
    Swagger,
    MilkDrink,
    Spark,
    FuryCutter,
    SteelWing,
    MeanLook,
    Attract,
    SleepTalk,
    HealBell,
    Return,
    Present,
    Frustration,
    Safeguard,
    PainSplit,
    SacredFire,
    Magnitude,
    DynamicPunch,
    Megahorn,
    DragonBreath,
    BatonPass,
    Encore,
    Pursuit,
    RapidSpin,
    SweetScent,
    IronTail,
    MetalClaw,
    VitalThrow,
    MorningSun,
    Synthesis,
    Moonlight,
    HiddenPower,
    CrossChop,
    Twister,
    RainDance,
    SunnyDay,
    Crunch,
    MirrorCoat,
    PsychUp,
    ExtremeSpeed,
    AncientPower,
    ShadowBall,
    FutureSight,
    RockSmash,
    Whirlpool,
    BeatUp,

    const data = [_]Move{
        Move{
            // Pound
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        Move{
            // KarateChop
            .bp = 50,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        Move{
            // DoubleSlap
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        Move{
            // CometPunch
            .bp = 18,
            .type = .Normal,
            .accuracy = 85,
            .pp = 3, // * 5 = 15
        },
        Move{
            // MegaPunch
            .bp = 80,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        Move{
            // PayDay
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // FirePunch
            .bp = 75,
            .type = .Fire,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        Move{
            // IcePunch
            .bp = 75,
            .type = .Ice,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        Move{
            // ThunderPunch
            .bp = 75,
            .type = .Electric,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        Move{
            // Scratch
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        Move{
            // ViseGrip
            .bp = 55,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Guillotine
            .bp = 0,
            .type = .Normal,
            .accuracy = 30,
            .pp = 1, // * 5 = 5
        },
        Move{
            // RazorWind
            .bp = 80,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        Move{
            // SwordsDance
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Cut
            .bp = 50,
            .type = .Normal,
            .accuracy = 95,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Gust
            .bp = 40,
            .type = .Flying,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        Move{
            // WingAttack
            .bp = 60,
            .type = .Flying,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        Move{
            // Whirlwind
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Fly
            .bp = 70,
            .type = .Flying,
            .accuracy = 95,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Bind
            .bp = 15,
            .type = .Normal,
            .accuracy = 75,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Slam
            .bp = 80,
            .type = .Normal,
            .accuracy = 75,
            .pp = 4, // * 5 = 20
        },
        Move{
            // VineWhip
            .bp = 35,
            .type = .Grass,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Stomp
            .bp = 65,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        Move{
            // DoubleKick
            .bp = 30,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // MegaKick
            .bp = 120,
            .type = .Normal,
            .accuracy = 75,
            .pp = 1, // * 5 = 5
        },
        Move{
            // JumpKick
            .bp = 70,
            .type = .Fighting,
            .accuracy = 95,
            .pp = 5, // * 5 = 25
        },
        Move{
            // RollingKick
            .bp = 60,
            .type = .Fighting,
            .accuracy = 85,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        Move{
            // SandAttack
            .bp = 0,
            .type = .Ground,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Headbutt
            .bp = 70,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        Move{
            // HornAttack
            .bp = 65,
            .type = .Normal,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        Move{
            // FuryAttack
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        Move{
            // HornDrill
            .bp = 0,
            .type = .Normal,
            .accuracy = 30,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Tackle
            .bp = 35,
            .type = .Normal,
            .accuracy = 95,
            .pp = 7, // * 5 = 35
        },
        Move{
            // BodySlam
            .bp = 85,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        Move{
            // Wrap
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        Move{
            // TakeDown
            .bp = 90,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Thrash
            .bp = 90,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // DoubleEdge
            .bp = 120,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // TailWhip
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // PoisonSting
            .bp = 15,
            .type = .Poison,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
            .chance = 3, // * 10 = 30
        },
        Move{
            // Twineedle
            .bp = 25,
            .type = .Bug,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 2, // * 10 = 20
        },
        Move{
            // PinMissile
            .bp = 14,
            .type = .Bug,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Leer
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Bite
            .bp = 60,
            .type = .Dark,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 3, // * 10 = 30
        },
        Move{
            // Growl
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Roar
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Sing
            .bp = 0,
            .type = .Normal,
            .accuracy = 55,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Supersonic
            .bp = 0,
            .type = .Normal,
            .accuracy = 55,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SonicBoom
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Disable
            .bp = 0,
            .type = .Normal,
            .accuracy = 55,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Acid
            .bp = 40,
            .type = .Poison,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 1, // * 10 = 10
        },
        Move{
            // Ember
            .bp = 40,
            .type = .Fire,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        Move{
            // Flamethrower
            .bp = 95,
            .type = .Fire,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        Move{
            // Mist
            .bp = 0,
            .type = .Ice,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // WaterGun
            .bp = 40,
            .type = .Water,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        Move{
            // HydroPump
            .bp = 120,
            .type = .Water,
            .accuracy = 80,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Surf
            .bp = 95,
            .type = .Water,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // IceBeam
            .bp = 95,
            .type = .Ice,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 1, // * 10 = 10
        },
        Move{
            // Blizzard
            .bp = 120,
            .type = .Ice,
            .accuracy = 70,
            .pp = 1, // * 5 = 5
            .chance = 1, // * 10 = 10
        },
        Move{
            // Psybeam
            .bp = 65,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        Move{
            // BubbleBeam
            .bp = 65,
            .type = .Water,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        Move{
            // AuroraBeam
            .bp = 65,
            .type = .Ice,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        Move{
            // HyperBeam
            .bp = 150,
            .type = .Normal,
            .accuracy = 90,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Peck
            .bp = 35,
            .type = .Flying,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
        },
        Move{
            // DrillPeck
            .bp = 80,
            .type = .Flying,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Submission
            .bp = 80,
            .type = .Fighting,
            .accuracy = 80,
            .pp = 5, // * 5 = 25
        },
        Move{
            // LowKick
            .bp = 50,
            .type = .Fighting,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        Move{
            // Counter
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SeismicToss
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Strength
            .bp = 80,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Absorb
            .bp = 20,
            .type = .Grass,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // MegaDrain
            .bp = 40,
            .type = .Grass,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // LeechSeed
            .bp = 0,
            .type = .Grass,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Growth
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // RazorLeaf
            .bp = 55,
            .type = .Grass,
            .accuracy = 95,
            .pp = 5, // * 5 = 25
        },
        Move{
            // SolarBeam
            .bp = 120,
            .type = .Grass,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // PoisonPowder
            .bp = 0,
            .type = .Poison,
            .accuracy = 75,
            .pp = 7, // * 5 = 35
        },
        Move{
            // StunSpore
            .bp = 0,
            .type = .Grass,
            .accuracy = 75,
            .pp = 6, // * 5 = 30
        },
        Move{
            // SleepPowder
            .bp = 0,
            .type = .Grass,
            .accuracy = 75,
            .pp = 3, // * 5 = 15
        },
        Move{
            // PetalDance
            .bp = 70,
            .type = .Grass,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // StringShot
            .bp = 0,
            .type = .Bug,
            .accuracy = 95,
            .pp = 8, // * 5 = 40
        },
        Move{
            // DragonRage
            .bp = 0,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // FireSpin
            .bp = 15,
            .type = .Fire,
            .accuracy = 70,
            .pp = 3, // * 5 = 15
        },
        Move{
            // ThunderShock
            .bp = 40,
            .type = .Electric,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 1, // * 10 = 10
        },
        Move{
            // Thunderbolt
            .bp = 95,
            .type = .Electric,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        Move{
            // ThunderWave
            .bp = 0,
            .type = .Electric,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Thunder
            .bp = 120,
            .type = .Electric,
            .accuracy = 70,
            .pp = 2, // * 5 = 10
            .chance = 3, // * 10 = 30
        },
        Move{
            // RockThrow
            .bp = 50,
            .type = .Rock,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Earthquake
            .bp = 100,
            .type = .Ground,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Fissure
            .bp = 0,
            .type = .Ground,
            .accuracy = 30,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Dig
            .bp = 60,
            .type = .Ground,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Toxic
            .bp = 0,
            .type = .Poison,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Confusion
            .bp = 50,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        Move{
            // Psychic
            .bp = 90,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 1, // * 10 = 10
        },
        Move{
            // Hypnosis
            .bp = 0,
            .type = .Psychic,
            .accuracy = 60,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Meditate
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Agility
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // QuickAttack
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Rage
            .bp = 20,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Teleport
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // NightShade
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Mimic
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Screech
            .bp = 0,
            .type = .Normal,
            .accuracy = 85,
            .pp = 8, // * 5 = 40
        },
        Move{
            // DoubleTeam
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Recover
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Harden
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Minimize
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Smokescreen
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // ConfuseRay
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Withdraw
            .bp = 0,
            .type = .Water,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // DefenseCurl
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Barrier
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // LightScreen
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Haze
            .bp = 0,
            .type = .Ice,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Reflect
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // FocusEnergy
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Bide
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Metronome
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // MirrorMove
            .bp = 0,
            .type = .Flying,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SelfDestruct
            .bp = 200,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // EggBomb
            .bp = 100,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Lick
            .bp = 20,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 3, // * 10 = 30
        },
        Move{
            // Smog
            .bp = 20,
            .type = .Poison,
            .accuracy = 70,
            .pp = 4, // * 5 = 20
            .chance = 4, // * 10 = 40
        },
        Move{
            // Sludge
            .bp = 65,
            .type = .Poison,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        Move{
            // BoneClub
            .bp = 65,
            .type = .Ground,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
            .chance = 1, // * 10 = 10
        },
        Move{
            // FireBlast
            .bp = 120,
            .type = .Fire,
            .accuracy = 85,
            .pp = 1, // * 5 = 5
            .chance = 1, // * 10 = 10
        },
        Move{
            // Waterfall
            .bp = 80,
            .type = .Water,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Clamp
            .bp = 35,
            .type = .Water,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Swift
            .bp = 60,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SkullBash
            .bp = 100,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // SpikeCannon
            .bp = 20,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Constrict
            .bp = 10,
            .type = .Normal,
            .accuracy = 100,
            .pp = 7, // * 5 = 35
            .chance = 1, // * 10 = 10
        },
        Move{
            // Amnesia
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Kinesis
            .bp = 0,
            .type = .Psychic,
            .accuracy = 80,
            .pp = 3, // * 5 = 15
        },
        Move{
            // SoftBoiled
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // HighJumpKick
            .bp = 85,
            .type = .Fighting,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Glare
            .bp = 0,
            .type = .Normal,
            .accuracy = 75,
            .pp = 6, // * 5 = 30
        },
        Move{
            // DreamEater
            .bp = 100,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // PoisonGas
            .bp = 0,
            .type = .Poison,
            .accuracy = 55,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Barrage
            .bp = 15,
            .type = .Normal,
            .accuracy = 85,
            .pp = 4, // * 5 = 20
        },
        Move{
            // LeechLife
            .bp = 20,
            .type = .Bug,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // LovelyKiss
            .bp = 0,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        Move{
            // SkyAttack
            .bp = 140,
            .type = .Flying,
            .accuracy = 90,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Transform
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Bubble
            .bp = 20,
            .type = .Water,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
            .chance = 1, // * 10 = 10
        },
        Move{
            // DizzyPunch
            .bp = 70,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 2, // * 10 = 20
        },
        Move{
            // Spore
            .bp = 0,
            .type = .Grass,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Flash
            .bp = 0,
            .type = .Normal,
            .accuracy = 70,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Psywave
            .bp = 0,
            .type = .Psychic,
            .accuracy = 80,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Splash
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // AcidArmor
            .bp = 0,
            .type = .Poison,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Crabhammer
            .bp = 90,
            .type = .Water,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Explosion
            .bp = 250,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // FurySwipes
            .bp = 18,
            .type = .Normal,
            .accuracy = 80,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Bonemerang
            .bp = 50,
            .type = .Ground,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Rest
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // RockSlide
            .bp = 75,
            .type = .Rock,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
            .chance = 3, // * 10 = 30
        },
        Move{
            // HyperFang
            .bp = 80,
            .type = .Normal,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
            .chance = 1, // * 10 = 10
        },
        Move{
            // Sharpen
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Conversion
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // TriAttack
            .bp = 80,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 2, // * 10 = 20
        },
        Move{
            // SuperFang
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Slash
            .bp = 70,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Substitute
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Struggle
            .bp = 50,
            .type = .Normal,
            .accuracy = 100,
            .pp = 0, // = 1
        },
        Move{
            // Sketch
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 0, // = 1
        },
        Move{
            // TripleKick
            .bp = 10,
            .type = .Fighting,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Thief
            .bp = 40,
            .type = .Dark,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 10, // * 10 = 100
        },
        Move{
            // SpiderWeb
            .bp = 0,
            .type = .Bug,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // MindReader
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Nightmare
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // FlameWheel
            .bp = 60,
            .type = .Fire,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        Move{
            // Snore
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        Move{
            // Curse
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Flail
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Conversion2
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // Aeroblast
            .bp = 100,
            .type = .Flying,
            .accuracy = 95,
            .pp = 1, // * 5 = 5
        },
        Move{
            // CottonSpore
            .bp = 0,
            .type = .Grass,
            .accuracy = 85,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Reversal
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Spite
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // PowderSnow
            .bp = 40,
            .type = .Ice,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        Move{
            // Protect
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // MachPunch
            .bp = 40,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // ScaryFace
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 2, // * 5 = 10
        },
        Move{
            // FeintAttack
            .bp = 60,
            .type = .Dark,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SweetKiss
            .bp = 0,
            .type = .Normal,
            .accuracy = 75,
            .pp = 2, // * 5 = 10
        },
        Move{
            // BellyDrum
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // SludgeBomb
            .bp = 90,
            .type = .Poison,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 3, // * 10 = 30
        },
        Move{
            // MudSlap
            .bp = 20,
            .type = .Ground,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
            .chance = 10, // * 10 = 100
        },
        Move{
            // Octazooka
            .bp = 65,
            .type = .Water,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
            .chance = 5, // * 10 = 50
        },
        Move{
            // Spikes
            .bp = 0,
            .type = .Ground,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // ZapCannon
            .bp = 100,
            .type = .Electric,
            .accuracy = 50,
            .pp = 1, // * 5 = 5
            .chance = 10, // * 10 = 100
        },
        Move{
            // Foresight
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // DestinyBond
            .bp = 0,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // PerishSong
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // IcyWind
            .bp = 55,
            .type = .Ice,
            .accuracy = 95,
            .pp = 3, // * 5 = 15
            .chance = 10, // * 10 = 100
        },
        Move{
            // Detect
            .bp = 0,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // BoneRush
            .bp = 25,
            .type = .Ground,
            .accuracy = 80,
            .pp = 2, // * 5 = 10
        },
        Move{
            // LockOn
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Outrage
            .bp = 90,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Sandstorm
            .bp = 0,
            .type = .Rock,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // GigaDrain
            .bp = 60,
            .type = .Grass,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Endure
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Charm
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Rollout
            .bp = 30,
            .type = .Rock,
            .accuracy = 90,
            .pp = 4, // * 5 = 20
        },
        Move{
            // FalseSwipe
            .bp = 40,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Swagger
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        Move{
            // MilkDrink
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // Spark
            .bp = 65,
            .type = .Electric,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        Move{
            // FuryCutter
            .bp = 10,
            .type = .Bug,
            .accuracy = 95,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SteelWing
            .bp = 70,
            .type = .Steel,
            .accuracy = 90,
            .pp = 5, // * 5 = 25
            .chance = 1, // * 10 = 10
        },
        Move{
            // MeanLook
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Attract
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // SleepTalk
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // HealBell
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Return
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Present
            .bp = 0,
            .type = .Normal,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        Move{
            // Frustration
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // Safeguard
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 5, // * 5 = 25
        },
        Move{
            // PainSplit
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // SacredFire
            .bp = 100,
            .type = .Fire,
            .accuracy = 95,
            .pp = 1, // * 5 = 5
            .chance = 5, // * 10 = 50
        },
        Move{
            // Magnitude
            .bp = 0,
            .type = .Ground,
            .accuracy = 100,
            .pp = 6, // * 5 = 30
        },
        Move{
            // DynamicPunch
            .bp = 100,
            .type = .Fighting,
            .accuracy = 50,
            .pp = 1, // * 5 = 5
            .chance = 10, // * 10 = 100
        },
        Move{
            // Megahorn
            .bp = 120,
            .type = .Bug,
            .accuracy = 85,
            .pp = 2, // * 5 = 10
        },
        Move{
            // DragonBreath
            .bp = 60,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 3, // * 10 = 30
        },
        Move{
            // BatonPass
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // Encore
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Pursuit
            .bp = 40,
            .type = .Dark,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // RapidSpin
            .bp = 20,
            .type = .Normal,
            .accuracy = 100,
            .pp = 8, // * 5 = 40
        },
        Move{
            // SweetScent
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // IronTail
            .bp = 100,
            .type = .Steel,
            .accuracy = 75,
            .pp = 3, // * 5 = 15
            .chance = 3, // * 10 = 30
        },
        Move{
            // MetalClaw
            .bp = 50,
            .type = .Steel,
            .accuracy = 95,
            .pp = 7, // * 5 = 35
            .chance = 1, // * 10 = 10
        },
        Move{
            // VitalThrow
            .bp = 70,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // MorningSun
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Synthesis
            .bp = 0,
            .type = .Grass,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Moonlight
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // HiddenPower
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
        },
        Move{
            // CrossChop
            .bp = 100,
            .type = .Fighting,
            .accuracy = 80,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Twister
            .bp = 40,
            .type = .Dragon,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
            .chance = 2, // * 10 = 20
        },
        Move{
            // RainDance
            .bp = 0,
            .type = .Water,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // SunnyDay
            .bp = 0,
            .type = .Fire,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // Crunch
            .bp = 80,
            .type = .Dark,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 2, // * 10 = 20
        },
        Move{
            // MirrorCoat
            .bp = 0,
            .type = .Psychic,
            .accuracy = 100,
            .pp = 4, // * 5 = 20
        },
        Move{
            // PsychUp
            .bp = 0,
            .type = .Normal,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
        Move{
            // ExtremeSpeed
            .bp = 80,
            .type = .Normal,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
        },
        Move{
            // AncientPower
            .bp = 60,
            .type = .Rock,
            .accuracy = 100,
            .pp = 1, // * 5 = 5
            .chance = 1, // * 10 = 10
        },
        Move{
            // ShadowBall
            .bp = 80,
            .type = .Ghost,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 2, // * 10 = 20
        },
        Move{
            // FutureSight
            .bp = 80,
            .type = .Psychic,
            .accuracy = 90,
            .pp = 3, // * 5 = 15
        },
        Move{
            // RockSmash
            .bp = 20,
            .type = .Fighting,
            .accuracy = 100,
            .pp = 3, // * 5 = 15
            .chance = 5, // * 10 = 50
        },
        Move{
            // Whirlpool
            .bp = 15,
            .type = .Water,
            .accuracy = 70,
            .pp = 3, // * 5 = 15
        },
        Move{
            // BeatUp
            .bp = 10,
            .type = .Dark,
            .accuracy = 100,
            .pp = 2, // * 5 = 10
        },
    };

    comptime {
        assert(@sizeOf(Moves) == 1);
        assert(@sizeOf(@TypeOf(data)) == 1004);
    }

    pub fn get(id: Moves) Move {
        assert(id != .None);
        return data[@enumToInt(id) - 1];
    }
};
