//! Code generated by `tools/generate` - manual edits will be overwritten

const std = @import("std");
const gen2 = @import("../../gen2/data.zig");

const assert = std.debug.assert;

const Specie = gen2.Specie;
const Stats = gen2.Stats;
const Types = gen2.Types;

pub const Species = enum(u8) {
    None,
    Bulbasaur,
    Ivysaur,
    Venusaur,
    Charmander,
    Charmeleon,
    Charizard,
    Squirtle,
    Wartortle,
    Blastoise,
    Caterpie,
    Metapod,
    Butterfree,
    Weedle,
    Kakuna,
    Beedrill,
    Pidgey,
    Pidgeotto,
    Pidgeot,
    Rattata,
    Raticate,
    Spearow,
    Fearow,
    Ekans,
    Arbok,
    Pikachu,
    Raichu,
    Sandshrew,
    Sandslash,
    NidoranF,
    Nidorina,
    Nidoqueen,
    NidoranM,
    Nidorino,
    Nidoking,
    Clefairy,
    Clefable,
    Vulpix,
    Ninetales,
    Jigglypuff,
    Wigglytuff,
    Zubat,
    Golbat,
    Oddish,
    Gloom,
    Vileplume,
    Paras,
    Parasect,
    Venonat,
    Venomoth,
    Diglett,
    Dugtrio,
    Meowth,
    Persian,
    Psyduck,
    Golduck,
    Mankey,
    Primeape,
    Growlithe,
    Arcanine,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Abra,
    Kadabra,
    Alakazam,
    Machop,
    Machoke,
    Machamp,
    Bellsprout,
    Weepinbell,
    Victreebel,
    Tentacool,
    Tentacruel,
    Geodude,
    Graveler,
    Golem,
    Ponyta,
    Rapidash,
    Slowpoke,
    Slowbro,
    Magnemite,
    Magneton,
    Farfetchd,
    Doduo,
    Dodrio,
    Seel,
    Dewgong,
    Grimer,
    Muk,
    Shellder,
    Cloyster,
    Gastly,
    Haunter,
    Gengar,
    Onix,
    Drowzee,
    Hypno,
    Krabby,
    Kingler,
    Voltorb,
    Electrode,
    Exeggcute,
    Exeggutor,
    Cubone,
    Marowak,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing,
    Weezing,
    Rhyhorn,
    Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    Horsea,
    Seadra,
    Goldeen,
    Seaking,
    Staryu,
    Starmie,
    MrMime,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    Tauros,
    Magikarp,
    Gyarados,
    Lapras,
    Ditto,
    Eevee,
    Vaporeon,
    Jolteon,
    Flareon,
    Porygon,
    Omanyte,
    Omastar,
    Kabuto,
    Kabutops,
    Aerodactyl,
    Snorlax,
    Articuno,
    Zapdos,
    Moltres,
    Dratini,
    Dragonair,
    Dragonite,
    Mewtwo,
    Mew,
    Chikorita,
    Bayleef,
    Meganium,
    Cyndaquil,
    Quilava,
    Typhlosion,
    Totodile,
    Croconaw,
    Feraligatr,
    Sentret,
    Furret,
    Hoothoot,
    Noctowl,
    Ledyba,
    Ledian,
    Spinarak,
    Ariados,
    Crobat,
    Chinchou,
    Lanturn,
    Pichu,
    Cleffa,
    Igglybuff,
    Togepi,
    Togetic,
    Natu,
    Xatu,
    Mareep,
    Flaaffy,
    Ampharos,
    Bellossom,
    Marill,
    Azumarill,
    Sudowoodo,
    Politoed,
    Hoppip,
    Skiploom,
    Jumpluff,
    Aipom,
    Sunkern,
    Sunflora,
    Yanma,
    Wooper,
    Quagsire,
    Espeon,
    Umbreon,
    Murkrow,
    Slowking,
    Misdreavus,
    Unown,
    Wobbuffet,
    Girafarig,
    Pineco,
    Forretress,
    Dunsparce,
    Gligar,
    Steelix,
    Snubbull,
    Granbull,
    Qwilfish,
    Scizor,
    Shuckle,
    Heracross,
    Sneasel,
    Teddiursa,
    Ursaring,
    Slugma,
    Magcargo,
    Swinub,
    Piloswine,
    Corsola,
    Remoraid,
    Octillery,
    Delibird,
    Mantine,
    Skarmory,
    Houndour,
    Houndoom,
    Kingdra,
    Phanpy,
    Donphan,
    Porygon2,
    Stantler,
    Smeargle,
    Tyrogue,
    Hitmontop,
    Smoochum,
    Elekid,
    Magby,
    Miltank,
    Blissey,
    Raikou,
    Entei,
    Suicune,
    Larvitar,
    Pupitar,
    Tyranitar,
    Lugia,
    HoOh,
    Celebi,

    // @test-only
    const data = [_]Specie{
        Specie{
            // Bulbasaur,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 49,
                .def = 49,
                .spe = 45,
                .spa = 65,
                .spd = 65,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Ivysaur,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 62,
                .def = 63,
                .spe = 60,
                .spa = 80,
                .spd = 80,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Venusaur,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 82,
                .def = 83,
                .spe = 80,
                .spa = 100,
                .spd = 100,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Charmander,
            .stats = Stats(u8){
                .hp = 39,
                .atk = 52,
                .def = 43,
                .spe = 65,
                .spa = 60,
                .spd = 50,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Charmeleon,
            .stats = Stats(u8){
                .hp = 58,
                .atk = 64,
                .def = 58,
                .spe = 80,
                .spa = 80,
                .spd = 65,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Charizard,
            .stats = Stats(u8){
                .hp = 78,
                .atk = 84,
                .def = 78,
                .spe = 100,
                .spa = 109,
                .spd = 85,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Flying },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Squirtle,
            .stats = Stats(u8){
                .hp = 44,
                .atk = 48,
                .def = 65,
                .spe = 43,
                .spa = 50,
                .spd = 64,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Wartortle,
            .stats = Stats(u8){
                .hp = 59,
                .atk = 63,
                .def = 80,
                .spe = 58,
                .spa = 65,
                .spd = 80,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Blastoise,
            .stats = Stats(u8){
                .hp = 79,
                .atk = 83,
                .def = 100,
                .spe = 78,
                .spa = 85,
                .spd = 105,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Caterpie,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 30,
                .def = 35,
                .spe = 45,
                .spa = 20,
                .spd = 20,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Bug },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Metapod,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 20,
                .def = 55,
                .spe = 30,
                .spa = 25,
                .spd = 25,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Bug },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Butterfree,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 45,
                .def = 50,
                .spe = 70,
                .spa = 80,
                .spd = 80,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Weedle,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 35,
                .def = 30,
                .spe = 50,
                .spa = 20,
                .spd = 20,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Kakuna,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 25,
                .def = 50,
                .spe = 35,
                .spa = 25,
                .spd = 25,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Beedrill,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 80,
                .def = 40,
                .spe = 75,
                .spa = 45,
                .spd = 80,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pidgey,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 45,
                .def = 40,
                .spe = 56,
                .spa = 35,
                .spd = 35,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pidgeotto,
            .stats = Stats(u8){
                .hp = 63,
                .atk = 60,
                .def = 55,
                .spe = 71,
                .spa = 50,
                .spd = 50,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pidgeot,
            .stats = Stats(u8){
                .hp = 83,
                .atk = 80,
                .def = 75,
                .spe = 91,
                .spa = 70,
                .spd = 70,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Rattata,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 56,
                .def = 35,
                .spe = 72,
                .spa = 25,
                .spd = 35,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Raticate,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 81,
                .def = 60,
                .spe = 97,
                .spa = 50,
                .spd = 70,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Spearow,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 60,
                .def = 30,
                .spe = 70,
                .spa = 31,
                .spd = 31,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Fearow,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 90,
                .def = 65,
                .spe = 100,
                .spa = 61,
                .spd = 61,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ekans,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 60,
                .def = 44,
                .spe = 55,
                .spa = 40,
                .spd = 54,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Arbok,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 85,
                .def = 69,
                .spe = 80,
                .spa = 65,
                .spd = 79,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pikachu,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 55,
                .def = 30,
                .spe = 90,
                .spa = 50,
                .spd = 40,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Raichu,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 90,
                .def = 55,
                .spe = 100,
                .spa = 90,
                .spd = 80,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Sandshrew,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 75,
                .def = 85,
                .spe = 40,
                .spa = 20,
                .spd = 30,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Sandslash,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 100,
                .def = 110,
                .spe = 65,
                .spa = 45,
                .spd = 55,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // NidoranF,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 47,
                .def = 52,
                .spe = 41,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Nidorina,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 62,
                .def = 67,
                .spe = 56,
                .spa = 55,
                .spd = 55,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Nidoqueen,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 82,
                .def = 87,
                .spe = 76,
                .spa = 75,
                .spd = 85,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Ground },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // NidoranM,
            .stats = Stats(u8){
                .hp = 46,
                .atk = 57,
                .def = 40,
                .spe = 50,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Nidorino,
            .stats = Stats(u8){
                .hp = 61,
                .atk = 72,
                .def = 57,
                .spe = 65,
                .spa = 55,
                .spd = 55,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Nidoking,
            .stats = Stats(u8){
                .hp = 81,
                .atk = 92,
                .def = 77,
                .spe = 85,
                .spa = 85,
                .spd = 75,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Ground },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Clefairy,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 45,
                .def = 48,
                .spe = 35,
                .spa = 60,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Clefable,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 70,
                .def = 73,
                .spe = 60,
                .spa = 85,
                .spd = 90,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Vulpix,
            .stats = Stats(u8){
                .hp = 38,
                .atk = 41,
                .def = 40,
                .spe = 65,
                .spa = 50,
                .spd = 65,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Ninetales,
            .stats = Stats(u8){
                .hp = 73,
                .atk = 76,
                .def = 75,
                .spe = 100,
                .spa = 81,
                .spd = 100,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Jigglypuff,
            .stats = Stats(u8){
                .hp = 115,
                .atk = 45,
                .def = 20,
                .spe = 20,
                .spa = 45,
                .spd = 25,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Wigglytuff,
            .stats = Stats(u8){
                .hp = 140,
                .atk = 70,
                .def = 45,
                .spe = 45,
                .spa = 75,
                .spd = 50,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Zubat,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 45,
                .def = 35,
                .spe = 55,
                .spa = 30,
                .spd = 40,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Golbat,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 80,
                .def = 70,
                .spe = 90,
                .spa = 65,
                .spd = 75,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Oddish,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 50,
                .def = 55,
                .spe = 30,
                .spa = 75,
                .spd = 65,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Gloom,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 65,
                .def = 70,
                .spe = 40,
                .spa = 85,
                .spd = 75,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Vileplume,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 80,
                .def = 85,
                .spe = 50,
                .spa = 100,
                .spd = 90,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Paras,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 70,
                .def = 55,
                .spe = 25,
                .spa = 45,
                .spd = 55,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Grass },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Parasect,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 95,
                .def = 80,
                .spe = 30,
                .spa = 60,
                .spd = 80,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Grass },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Venonat,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 55,
                .def = 50,
                .spe = 45,
                .spa = 40,
                .spd = 55,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Venomoth,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 65,
                .def = 60,
                .spe = 90,
                .spa = 90,
                .spd = 75,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Diglett,
            .stats = Stats(u8){
                .hp = 10,
                .atk = 55,
                .def = 25,
                .spe = 95,
                .spa = 35,
                .spd = 45,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Dugtrio,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 80,
                .def = 50,
                .spe = 120,
                .spa = 50,
                .spd = 70,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Meowth,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 45,
                .def = 35,
                .spe = 90,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Persian,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 70,
                .def = 60,
                .spe = 115,
                .spa = 65,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Psyduck,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 52,
                .def = 48,
                .spe = 55,
                .spa = 65,
                .spd = 50,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Golduck,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 82,
                .def = 78,
                .spe = 85,
                .spa = 95,
                .spd = 80,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Mankey,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 80,
                .def = 35,
                .spe = 70,
                .spa = 35,
                .spd = 45,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Primeape,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 105,
                .def = 60,
                .spe = 95,
                .spa = 60,
                .spd = 70,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Growlithe,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 70,
                .def = 45,
                .spe = 60,
                .spa = 70,
                .spd = 50,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Arcanine,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 110,
                .def = 80,
                .spe = 95,
                .spa = 100,
                .spd = 80,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Poliwag,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 50,
                .def = 40,
                .spe = 90,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Poliwhirl,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 65,
                .def = 65,
                .spe = 90,
                .spa = 50,
                .spd = 50,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Poliwrath,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 85,
                .def = 95,
                .spe = 70,
                .spa = 70,
                .spd = 90,
            },
            .types = Types{ .type1 = .Water, .type2 = .Fighting },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Abra,
            .stats = Stats(u8){
                .hp = 25,
                .atk = 20,
                .def = 15,
                .spe = 90,
                .spa = 105,
                .spd = 55,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Kadabra,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 35,
                .def = 30,
                .spe = 105,
                .spa = 120,
                .spd = 70,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Alakazam,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 50,
                .def = 45,
                .spe = 120,
                .spa = 135,
                .spd = 85,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Machop,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 80,
                .def = 50,
                .spe = 35,
                .spa = 35,
                .spd = 35,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Machoke,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 100,
                .def = 70,
                .spe = 45,
                .spa = 50,
                .spd = 60,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Machamp,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 130,
                .def = 80,
                .spe = 55,
                .spa = 65,
                .spd = 85,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Bellsprout,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 75,
                .def = 35,
                .spe = 40,
                .spa = 70,
                .spd = 30,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Weepinbell,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 90,
                .def = 50,
                .spe = 55,
                .spa = 85,
                .spd = 45,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Victreebel,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 105,
                .def = 65,
                .spe = 70,
                .spa = 100,
                .spd = 60,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Tentacool,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 40,
                .def = 35,
                .spe = 70,
                .spa = 50,
                .spd = 100,
            },
            .types = Types{ .type1 = .Water, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Tentacruel,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 70,
                .def = 65,
                .spe = 100,
                .spa = 80,
                .spd = 120,
            },
            .types = Types{ .type1 = .Water, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Geodude,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 80,
                .def = 100,
                .spe = 20,
                .spa = 30,
                .spd = 30,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Graveler,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 95,
                .def = 115,
                .spe = 35,
                .spa = 45,
                .spd = 45,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Golem,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 110,
                .def = 130,
                .spe = 45,
                .spa = 55,
                .spd = 65,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ponyta,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 85,
                .def = 55,
                .spe = 90,
                .spa = 65,
                .spd = 65,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Rapidash,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 100,
                .def = 70,
                .spe = 105,
                .spa = 80,
                .spd = 80,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Slowpoke,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 65,
                .def = 65,
                .spe = 15,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Water, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Slowbro,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 75,
                .def = 110,
                .spe = 30,
                .spa = 100,
                .spd = 80,
            },
            .types = Types{ .type1 = .Water, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Magnemite,
            .stats = Stats(u8){
                .hp = 25,
                .atk = 35,
                .def = 70,
                .spe = 45,
                .spa = 95,
                .spd = 55,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Steel },
            .ratio = 0xFF, // N
        },
        Specie{
            // Magneton,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 60,
                .def = 95,
                .spe = 70,
                .spa = 120,
                .spd = 70,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Steel },
            .ratio = 0xFF, // N
        },
        Specie{
            // Farfetchd,
            .stats = Stats(u8){
                .hp = 52,
                .atk = 65,
                .def = 55,
                .spe = 60,
                .spa = 58,
                .spd = 62,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Doduo,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 85,
                .def = 45,
                .spe = 75,
                .spa = 35,
                .spd = 35,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Dodrio,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 110,
                .def = 70,
                .spe = 100,
                .spa = 60,
                .spd = 60,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Seel,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 45,
                .def = 55,
                .spe = 45,
                .spa = 45,
                .spd = 70,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Dewgong,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 70,
                .def = 80,
                .spe = 70,
                .spa = 70,
                .spd = 95,
            },
            .types = Types{ .type1 = .Water, .type2 = .Ice },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Grimer,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 80,
                .def = 50,
                .spe = 25,
                .spa = 40,
                .spd = 50,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Muk,
            .stats = Stats(u8){
                .hp = 105,
                .atk = 105,
                .def = 75,
                .spe = 50,
                .spa = 65,
                .spd = 100,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Shellder,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 65,
                .def = 100,
                .spe = 40,
                .spa = 45,
                .spd = 25,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Cloyster,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 95,
                .def = 180,
                .spe = 70,
                .spa = 85,
                .spd = 45,
            },
            .types = Types{ .type1 = .Water, .type2 = .Ice },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Gastly,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 35,
                .def = 30,
                .spe = 80,
                .spa = 100,
                .spd = 35,
            },
            .types = Types{ .type1 = .Ghost, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Haunter,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 50,
                .def = 45,
                .spe = 95,
                .spa = 115,
                .spd = 55,
            },
            .types = Types{ .type1 = .Ghost, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Gengar,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 65,
                .def = 60,
                .spe = 110,
                .spa = 130,
                .spd = 75,
            },
            .types = Types{ .type1 = .Ghost, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Onix,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 45,
                .def = 160,
                .spe = 70,
                .spa = 30,
                .spd = 45,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Drowzee,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 48,
                .def = 45,
                .spe = 42,
                .spa = 43,
                .spd = 90,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Hypno,
            .stats = Stats(u8){
                .hp = 85,
                .atk = 73,
                .def = 70,
                .spe = 67,
                .spa = 73,
                .spd = 115,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Krabby,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 105,
                .def = 90,
                .spe = 50,
                .spa = 25,
                .spd = 25,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Kingler,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 130,
                .def = 115,
                .spe = 75,
                .spa = 50,
                .spd = 50,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Voltorb,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 30,
                .def = 50,
                .spe = 100,
                .spa = 55,
                .spd = 55,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0xFF, // N
        },
        Specie{
            // Electrode,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 50,
                .def = 70,
                .spe = 140,
                .spa = 80,
                .spd = 80,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0xFF, // N
        },
        Specie{
            // Exeggcute,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 40,
                .def = 80,
                .spe = 40,
                .spa = 60,
                .spd = 45,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Exeggutor,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 95,
                .def = 85,
                .spe = 55,
                .spa = 125,
                .spd = 65,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Cubone,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 50,
                .def = 95,
                .spe = 35,
                .spa = 40,
                .spd = 50,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Marowak,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 80,
                .def = 110,
                .spe = 45,
                .spa = 50,
                .spd = 80,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Hitmonlee,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 120,
                .def = 53,
                .spe = 87,
                .spa = 35,
                .spd = 110,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Hitmonchan,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 105,
                .def = 79,
                .spe = 76,
                .spa = 35,
                .spd = 110,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Lickitung,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 55,
                .def = 75,
                .spe = 30,
                .spa = 60,
                .spd = 75,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Koffing,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 65,
                .def = 95,
                .spe = 35,
                .spa = 60,
                .spd = 45,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Weezing,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 90,
                .def = 120,
                .spe = 60,
                .spa = 85,
                .spd = 70,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Rhyhorn,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 85,
                .def = 95,
                .spe = 25,
                .spa = 30,
                .spd = 30,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Rock },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Rhydon,
            .stats = Stats(u8){
                .hp = 105,
                .atk = 130,
                .def = 120,
                .spe = 40,
                .spa = 45,
                .spd = 45,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Rock },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Chansey,
            .stats = Stats(u8){
                .hp = 250,
                .atk = 5,
                .def = 5,
                .spe = 50,
                .spa = 35,
                .spd = 105,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Tangela,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 55,
                .def = 115,
                .spe = 60,
                .spa = 100,
                .spd = 40,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Kangaskhan,
            .stats = Stats(u8){
                .hp = 105,
                .atk = 95,
                .def = 80,
                .spe = 90,
                .spa = 40,
                .spd = 80,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Horsea,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 40,
                .def = 70,
                .spe = 60,
                .spa = 70,
                .spd = 25,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Seadra,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 65,
                .def = 95,
                .spe = 85,
                .spa = 95,
                .spd = 45,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Goldeen,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 67,
                .def = 60,
                .spe = 63,
                .spa = 35,
                .spd = 50,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Seaking,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 92,
                .def = 65,
                .spe = 68,
                .spa = 65,
                .spd = 80,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Staryu,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 45,
                .def = 55,
                .spe = 85,
                .spa = 70,
                .spd = 55,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0xFF, // N
        },
        Specie{
            // Starmie,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 75,
                .def = 85,
                .spe = 115,
                .spa = 100,
                .spd = 85,
            },
            .types = Types{ .type1 = .Water, .type2 = .Psychic },
            .ratio = 0xFF, // N
        },
        Specie{
            // MrMime,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 45,
                .def = 65,
                .spe = 90,
                .spa = 100,
                .spd = 120,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Scyther,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 110,
                .def = 80,
                .spe = 105,
                .spa = 55,
                .spd = 80,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Jynx,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 50,
                .def = 35,
                .spe = 95,
                .spa = 115,
                .spd = 95,
            },
            .types = Types{ .type1 = .Ice, .type2 = .Psychic },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Electabuzz,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 83,
                .def = 57,
                .spe = 105,
                .spa = 95,
                .spd = 85,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Magmar,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 95,
                .def = 57,
                .spe = 93,
                .spa = 100,
                .spd = 85,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Pinsir,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 125,
                .def = 100,
                .spe = 85,
                .spa = 55,
                .spd = 70,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Bug },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Tauros,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 100,
                .def = 95,
                .spe = 110,
                .spa = 40,
                .spd = 70,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Magikarp,
            .stats = Stats(u8){
                .hp = 20,
                .atk = 10,
                .def = 55,
                .spe = 80,
                .spa = 15,
                .spd = 20,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Gyarados,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 125,
                .def = 79,
                .spe = 81,
                .spa = 60,
                .spd = 100,
            },
            .types = Types{ .type1 = .Water, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Lapras,
            .stats = Stats(u8){
                .hp = 130,
                .atk = 85,
                .def = 80,
                .spe = 60,
                .spa = 85,
                .spd = 95,
            },
            .types = Types{ .type1 = .Water, .type2 = .Ice },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ditto,
            .stats = Stats(u8){
                .hp = 48,
                .atk = 48,
                .def = 48,
                .spe = 48,
                .spa = 48,
                .spd = 48,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFF, // N
        },
        Specie{
            // Eevee,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 55,
                .def = 50,
                .spe = 55,
                .spa = 45,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Vaporeon,
            .stats = Stats(u8){
                .hp = 130,
                .atk = 65,
                .def = 60,
                .spe = 65,
                .spa = 110,
                .spd = 95,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Jolteon,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 65,
                .def = 60,
                .spe = 130,
                .spa = 110,
                .spd = 95,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Flareon,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 130,
                .def = 60,
                .spe = 65,
                .spa = 95,
                .spd = 110,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Porygon,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 60,
                .def = 70,
                .spe = 40,
                .spa = 85,
                .spd = 75,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFF, // N
        },
        Specie{
            // Omanyte,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 40,
                .def = 100,
                .spe = 35,
                .spa = 90,
                .spd = 55,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Omastar,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 60,
                .def = 125,
                .spe = 55,
                .spa = 115,
                .spd = 70,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Kabuto,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 80,
                .def = 90,
                .spe = 55,
                .spa = 55,
                .spd = 45,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Kabutops,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 115,
                .def = 105,
                .spe = 80,
                .spa = 65,
                .spd = 70,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Aerodactyl,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 105,
                .def = 65,
                .spe = 130,
                .spa = 60,
                .spd = 75,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Flying },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Snorlax,
            .stats = Stats(u8){
                .hp = 160,
                .atk = 110,
                .def = 65,
                .spe = 30,
                .spa = 65,
                .spd = 110,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Articuno,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 85,
                .def = 100,
                .spe = 85,
                .spa = 95,
                .spd = 125,
            },
            .types = Types{ .type1 = .Ice, .type2 = .Flying },
            .ratio = 0xFF, // N
        },
        Specie{
            // Zapdos,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 90,
                .def = 85,
                .spe = 100,
                .spa = 125,
                .spd = 90,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Flying },
            .ratio = 0xFF, // N
        },
        Specie{
            // Moltres,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 100,
                .def = 90,
                .spe = 90,
                .spa = 125,
                .spd = 85,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Flying },
            .ratio = 0xFF, // N
        },
        Specie{
            // Dratini,
            .stats = Stats(u8){
                .hp = 41,
                .atk = 64,
                .def = 45,
                .spe = 50,
                .spa = 50,
                .spd = 50,
            },
            .types = Types{ .type1 = .Dragon, .type2 = .Dragon },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Dragonair,
            .stats = Stats(u8){
                .hp = 61,
                .atk = 84,
                .def = 65,
                .spe = 70,
                .spa = 70,
                .spd = 70,
            },
            .types = Types{ .type1 = .Dragon, .type2 = .Dragon },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Dragonite,
            .stats = Stats(u8){
                .hp = 91,
                .atk = 134,
                .def = 95,
                .spe = 80,
                .spa = 100,
                .spd = 100,
            },
            .types = Types{ .type1 = .Dragon, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Mewtwo,
            .stats = Stats(u8){
                .hp = 106,
                .atk = 110,
                .def = 90,
                .spe = 130,
                .spa = 154,
                .spd = 90,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0xFF, // N
        },
        Specie{
            // Mew,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 100,
                .def = 100,
                .spe = 100,
                .spa = 100,
                .spd = 100,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0xFF, // N
        },
        Specie{
            // Chikorita,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 49,
                .def = 65,
                .spe = 45,
                .spa = 49,
                .spd = 65,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Bayleef,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 62,
                .def = 80,
                .spe = 60,
                .spa = 63,
                .spd = 80,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Meganium,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 82,
                .def = 100,
                .spe = 80,
                .spa = 83,
                .spd = 100,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Cyndaquil,
            .stats = Stats(u8){
                .hp = 39,
                .atk = 52,
                .def = 43,
                .spe = 65,
                .spa = 60,
                .spd = 50,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Quilava,
            .stats = Stats(u8){
                .hp = 58,
                .atk = 64,
                .def = 58,
                .spe = 80,
                .spa = 80,
                .spd = 65,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Typhlosion,
            .stats = Stats(u8){
                .hp = 78,
                .atk = 84,
                .def = 78,
                .spe = 100,
                .spa = 109,
                .spd = 85,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Totodile,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 65,
                .def = 64,
                .spe = 43,
                .spa = 44,
                .spd = 48,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Croconaw,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 80,
                .def = 80,
                .spe = 58,
                .spa = 59,
                .spd = 63,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Feraligatr,
            .stats = Stats(u8){
                .hp = 85,
                .atk = 105,
                .def = 100,
                .spe = 78,
                .spa = 79,
                .spd = 83,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Sentret,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 46,
                .def = 34,
                .spe = 20,
                .spa = 35,
                .spd = 45,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Furret,
            .stats = Stats(u8){
                .hp = 85,
                .atk = 76,
                .def = 64,
                .spe = 90,
                .spa = 45,
                .spd = 55,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Hoothoot,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 30,
                .def = 30,
                .spe = 50,
                .spa = 36,
                .spd = 56,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Noctowl,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 50,
                .def = 50,
                .spe = 70,
                .spa = 76,
                .spd = 96,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ledyba,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 20,
                .def = 30,
                .spe = 55,
                .spa = 40,
                .spd = 80,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ledian,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 35,
                .def = 50,
                .spe = 85,
                .spa = 55,
                .spd = 110,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Spinarak,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 60,
                .def = 40,
                .spe = 30,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ariados,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 90,
                .def = 70,
                .spe = 40,
                .spa = 60,
                .spd = 60,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Crobat,
            .stats = Stats(u8){
                .hp = 85,
                .atk = 90,
                .def = 80,
                .spe = 130,
                .spa = 70,
                .spd = 80,
            },
            .types = Types{ .type1 = .Poison, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Chinchou,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 38,
                .def = 38,
                .spe = 67,
                .spa = 56,
                .spd = 56,
            },
            .types = Types{ .type1 = .Water, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Lanturn,
            .stats = Stats(u8){
                .hp = 125,
                .atk = 58,
                .def = 58,
                .spe = 67,
                .spa = 76,
                .spd = 76,
            },
            .types = Types{ .type1 = .Water, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pichu,
            .stats = Stats(u8){
                .hp = 20,
                .atk = 40,
                .def = 15,
                .spe = 60,
                .spa = 35,
                .spd = 35,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Cleffa,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 25,
                .def = 28,
                .spe = 15,
                .spa = 45,
                .spd = 55,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Igglybuff,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 30,
                .def = 15,
                .spe = 15,
                .spa = 40,
                .spd = 20,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Togepi,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 20,
                .def = 65,
                .spe = 20,
                .spa = 40,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Togetic,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 40,
                .def = 85,
                .spe = 40,
                .spa = 80,
                .spd = 105,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Flying },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Natu,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 50,
                .def = 45,
                .spe = 70,
                .spa = 70,
                .spd = 45,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Xatu,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 75,
                .def = 70,
                .spe = 95,
                .spa = 95,
                .spd = 70,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Mareep,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 40,
                .def = 40,
                .spe = 35,
                .spa = 65,
                .spd = 45,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Flaaffy,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 55,
                .def = 55,
                .spe = 45,
                .spa = 80,
                .spd = 60,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ampharos,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 75,
                .def = 75,
                .spe = 55,
                .spa = 115,
                .spd = 90,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Bellossom,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 80,
                .def = 85,
                .spe = 50,
                .spa = 90,
                .spd = 100,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Marill,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 20,
                .def = 50,
                .spe = 40,
                .spa = 20,
                .spd = 50,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Azumarill,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 50,
                .def = 80,
                .spe = 50,
                .spa = 50,
                .spd = 80,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Sudowoodo,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 100,
                .def = 115,
                .spe = 30,
                .spa = 30,
                .spd = 65,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Rock },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Politoed,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 75,
                .def = 75,
                .spe = 70,
                .spa = 90,
                .spd = 100,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Hoppip,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 35,
                .def = 40,
                .spe = 50,
                .spa = 35,
                .spd = 55,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Skiploom,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 45,
                .def = 50,
                .spe = 80,
                .spa = 45,
                .spd = 65,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Jumpluff,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 55,
                .def = 70,
                .spe = 110,
                .spa = 55,
                .spd = 85,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Aipom,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 70,
                .def = 55,
                .spe = 85,
                .spa = 40,
                .spd = 55,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Sunkern,
            .stats = Stats(u8){
                .hp = 30,
                .atk = 30,
                .def = 30,
                .spe = 30,
                .spa = 30,
                .spd = 30,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Sunflora,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 75,
                .def = 55,
                .spe = 30,
                .spa = 105,
                .spd = 85,
            },
            .types = Types{ .type1 = .Grass, .type2 = .Grass },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Yanma,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 65,
                .def = 45,
                .spe = 95,
                .spa = 75,
                .spd = 45,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Wooper,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 45,
                .def = 45,
                .spe = 15,
                .spa = 25,
                .spd = 25,
            },
            .types = Types{ .type1 = .Water, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Quagsire,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 85,
                .def = 85,
                .spe = 35,
                .spa = 65,
                .spd = 65,
            },
            .types = Types{ .type1 = .Water, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Espeon,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 65,
                .def = 60,
                .spe = 110,
                .spa = 130,
                .spd = 95,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Umbreon,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 65,
                .def = 110,
                .spe = 65,
                .spa = 60,
                .spd = 130,
            },
            .types = Types{ .type1 = .Dark, .type2 = .Dark },
            .ratio = 0x1F, // 12.5% F
        },
        Specie{
            // Murkrow,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 85,
                .def = 42,
                .spe = 91,
                .spa = 85,
                .spd = 42,
            },
            .types = Types{ .type1 = .Dark, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Slowking,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 75,
                .def = 80,
                .spe = 30,
                .spa = 100,
                .spd = 110,
            },
            .types = Types{ .type1 = .Water, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Misdreavus,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 60,
                .def = 60,
                .spe = 85,
                .spa = 85,
                .spd = 85,
            },
            .types = Types{ .type1 = .Ghost, .type2 = .Ghost },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Unown,
            .stats = Stats(u8){
                .hp = 48,
                .atk = 72,
                .def = 48,
                .spe = 48,
                .spa = 72,
                .spd = 48,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0xFF, // N
        },
        Specie{
            // Wobbuffet,
            .stats = Stats(u8){
                .hp = 190,
                .atk = 33,
                .def = 58,
                .spe = 33,
                .spa = 33,
                .spd = 58,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Girafarig,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 80,
                .def = 65,
                .spe = 85,
                .spa = 90,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Psychic },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pineco,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 65,
                .def = 90,
                .spe = 15,
                .spa = 35,
                .spd = 35,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Bug },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Forretress,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 90,
                .def = 140,
                .spe = 40,
                .spa = 60,
                .spd = 60,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Steel },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Dunsparce,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 70,
                .def = 70,
                .spe = 45,
                .spa = 65,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Gligar,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 75,
                .def = 105,
                .spe = 85,
                .spa = 35,
                .spd = 65,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Steelix,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 85,
                .def = 200,
                .spe = 30,
                .spa = 55,
                .spd = 65,
            },
            .types = Types{ .type1 = .Steel, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Snubbull,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 80,
                .def = 50,
                .spe = 30,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Granbull,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 120,
                .def = 75,
                .spe = 45,
                .spa = 60,
                .spd = 60,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Qwilfish,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 95,
                .def = 75,
                .spe = 85,
                .spa = 55,
                .spd = 55,
            },
            .types = Types{ .type1 = .Water, .type2 = .Poison },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Scizor,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 130,
                .def = 100,
                .spe = 65,
                .spa = 55,
                .spd = 80,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Steel },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Shuckle,
            .stats = Stats(u8){
                .hp = 20,
                .atk = 10,
                .def = 230,
                .spe = 5,
                .spa = 10,
                .spd = 230,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Rock },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Heracross,
            .stats = Stats(u8){
                .hp = 80,
                .atk = 125,
                .def = 75,
                .spe = 85,
                .spa = 40,
                .spd = 95,
            },
            .types = Types{ .type1 = .Bug, .type2 = .Fighting },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Sneasel,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 95,
                .def = 55,
                .spe = 115,
                .spa = 35,
                .spd = 75,
            },
            .types = Types{ .type1 = .Dark, .type2 = .Ice },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Teddiursa,
            .stats = Stats(u8){
                .hp = 60,
                .atk = 80,
                .def = 50,
                .spe = 40,
                .spa = 50,
                .spd = 50,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Ursaring,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 130,
                .def = 75,
                .spe = 55,
                .spa = 75,
                .spd = 75,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Slugma,
            .stats = Stats(u8){
                .hp = 40,
                .atk = 40,
                .def = 40,
                .spe = 20,
                .spa = 70,
                .spd = 40,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Magcargo,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 50,
                .def = 120,
                .spe = 30,
                .spa = 80,
                .spd = 80,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Rock },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Swinub,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 50,
                .def = 40,
                .spe = 50,
                .spa = 30,
                .spd = 30,
            },
            .types = Types{ .type1 = .Ice, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Piloswine,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 100,
                .def = 80,
                .spe = 50,
                .spa = 60,
                .spd = 60,
            },
            .types = Types{ .type1 = .Ice, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Corsola,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 55,
                .def = 85,
                .spe = 35,
                .spa = 65,
                .spd = 85,
            },
            .types = Types{ .type1 = .Water, .type2 = .Rock },
            .ratio = 0xBF, // 75.0% F
        },
        Specie{
            // Remoraid,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 65,
                .def = 35,
                .spe = 65,
                .spa = 65,
                .spd = 35,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Octillery,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 105,
                .def = 75,
                .spe = 45,
                .spa = 105,
                .spd = 75,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Delibird,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 55,
                .def = 45,
                .spe = 75,
                .spa = 65,
                .spd = 45,
            },
            .types = Types{ .type1 = .Ice, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Mantine,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 40,
                .def = 70,
                .spe = 70,
                .spa = 80,
                .spd = 140,
            },
            .types = Types{ .type1 = .Water, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Skarmory,
            .stats = Stats(u8){
                .hp = 65,
                .atk = 80,
                .def = 140,
                .spe = 70,
                .spa = 40,
                .spd = 70,
            },
            .types = Types{ .type1 = .Steel, .type2 = .Flying },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Houndour,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 60,
                .def = 30,
                .spe = 65,
                .spa = 80,
                .spd = 50,
            },
            .types = Types{ .type1 = .Dark, .type2 = .Fire },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Houndoom,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 90,
                .def = 50,
                .spe = 95,
                .spa = 110,
                .spd = 80,
            },
            .types = Types{ .type1 = .Dark, .type2 = .Fire },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Kingdra,
            .stats = Stats(u8){
                .hp = 75,
                .atk = 95,
                .def = 95,
                .spe = 85,
                .spa = 95,
                .spd = 95,
            },
            .types = Types{ .type1 = .Water, .type2 = .Dragon },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Phanpy,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 60,
                .def = 60,
                .spe = 40,
                .spa = 40,
                .spd = 40,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Donphan,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 120,
                .def = 120,
                .spe = 50,
                .spa = 60,
                .spd = 60,
            },
            .types = Types{ .type1 = .Ground, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Porygon2,
            .stats = Stats(u8){
                .hp = 85,
                .atk = 80,
                .def = 90,
                .spe = 60,
                .spa = 105,
                .spd = 95,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFF, // N
        },
        Specie{
            // Stantler,
            .stats = Stats(u8){
                .hp = 73,
                .atk = 95,
                .def = 62,
                .spe = 85,
                .spa = 85,
                .spd = 65,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Smeargle,
            .stats = Stats(u8){
                .hp = 55,
                .atk = 20,
                .def = 35,
                .spe = 75,
                .spa = 20,
                .spd = 45,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Tyrogue,
            .stats = Stats(u8){
                .hp = 35,
                .atk = 35,
                .def = 35,
                .spe = 35,
                .spa = 35,
                .spd = 35,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Hitmontop,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 95,
                .def = 95,
                .spe = 70,
                .spa = 35,
                .spd = 110,
            },
            .types = Types{ .type1 = .Fighting, .type2 = .Fighting },
            .ratio = 0x00, // 0.00% F
        },
        Specie{
            // Smoochum,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 30,
                .def = 15,
                .spe = 65,
                .spa = 85,
                .spd = 65,
            },
            .types = Types{ .type1 = .Ice, .type2 = .Psychic },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Elekid,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 63,
                .def = 37,
                .spe = 95,
                .spa = 65,
                .spd = 55,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Magby,
            .stats = Stats(u8){
                .hp = 45,
                .atk = 75,
                .def = 37,
                .spe = 83,
                .spa = 70,
                .spd = 55,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0x3F, // 25.0% F
        },
        Specie{
            // Miltank,
            .stats = Stats(u8){
                .hp = 95,
                .atk = 80,
                .def = 105,
                .spe = 100,
                .spa = 40,
                .spd = 70,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Blissey,
            .stats = Stats(u8){
                .hp = 255,
                .atk = 10,
                .def = 10,
                .spe = 55,
                .spa = 75,
                .spd = 135,
            },
            .types = Types{ .type1 = .Normal, .type2 = .Normal },
            .ratio = 0xFE, // 100% F
        },
        Specie{
            // Raikou,
            .stats = Stats(u8){
                .hp = 90,
                .atk = 85,
                .def = 75,
                .spe = 115,
                .spa = 115,
                .spd = 100,
            },
            .types = Types{ .type1 = .Electric, .type2 = .Electric },
            .ratio = 0xFF, // N
        },
        Specie{
            // Entei,
            .stats = Stats(u8){
                .hp = 115,
                .atk = 115,
                .def = 85,
                .spe = 100,
                .spa = 90,
                .spd = 75,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Fire },
            .ratio = 0xFF, // N
        },
        Specie{
            // Suicune,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 75,
                .def = 115,
                .spe = 85,
                .spa = 90,
                .spd = 115,
            },
            .types = Types{ .type1 = .Water, .type2 = .Water },
            .ratio = 0xFF, // N
        },
        Specie{
            // Larvitar,
            .stats = Stats(u8){
                .hp = 50,
                .atk = 64,
                .def = 50,
                .spe = 41,
                .spa = 45,
                .spd = 50,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Pupitar,
            .stats = Stats(u8){
                .hp = 70,
                .atk = 84,
                .def = 70,
                .spe = 51,
                .spa = 65,
                .spd = 70,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Ground },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Tyranitar,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 134,
                .def = 110,
                .spe = 61,
                .spa = 95,
                .spd = 100,
            },
            .types = Types{ .type1 = .Rock, .type2 = .Dark },
            .ratio = 0x7F, // 50.0% F
        },
        Specie{
            // Lugia,
            .stats = Stats(u8){
                .hp = 106,
                .atk = 90,
                .def = 130,
                .spe = 110,
                .spa = 90,
                .spd = 154,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Flying },
            .ratio = 0xFF, // N
        },
        Specie{
            // HoOh,
            .stats = Stats(u8){
                .hp = 106,
                .atk = 130,
                .def = 90,
                .spe = 90,
                .spa = 110,
                .spd = 154,
            },
            .types = Types{ .type1 = .Fire, .type2 = .Flying },
            .ratio = 0xFF, // N
        },
        Specie{
            // Celebi,
            .stats = Stats(u8){
                .hp = 100,
                .atk = 100,
                .def = 100,
                .spe = 100,
                .spa = 100,
                .spd = 100,
            },
            .types = Types{ .type1 = .Psychic, .type2 = .Grass },
            .ratio = 0xFF, // N
        },
    };

    comptime {
        assert(@sizeOf(Species) == 1);
    }

    // @test-only
    pub fn get(id: Species) Specie {
        assert(id != .None);
        return data[@enumToInt(id) - 1];
    }
};
